export interface Wine {
  name: string;
  slug: string;
  region_en: string;
  region_th: string;
  grape_varieties_en: string;
  grape_varieties_th: string;
  the_estate_en: string;
  the_estate_th: string;
  terroir_en: string;
  terroir_th: string;
  vinification_en: string;
  vinification_th: string;
  tasting_notes_en: string;
  tasting_notes_th: string;
  pairing_en: string;
  pairing_th: string;
  service_temperature: string;
  vintage: string;
  sku: string;
  abv: string;
  rating: string;
  price: string;
}

export interface WineRegion {
  region_slug: string;
  wines: Wine[];
}

export const winesByRegion: WineRegion[] = [
  {
    "region_slug": "champagne",
    "wines": [
      {
        "name": "Prestige des Sacres<br>Brut Nature Champagne",
        "slug": "prestige-des-sacres-brut-nature-champagne",
        "region_en": "Champagne, Montagne de Reims",
        "region_th": "แชมเปญ, มงตาญเดอแรงส์",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 0 g/L (no added sugar)<br>• Aged over 4 years in cellars, followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 0 กรัม/ลิตร (ไม่เติมน้ำตาล)<br>• หมักอายุกว่า 4 ปีในห้องเก็บ ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A brilliant pale gold color with rapid, energetic bubbles. The nose reveals biscuit and toasted almonds, with citrus and white flower notes. Aeration brings out minerality, white pepper, dried fruit, and honey. The palate is lively and pure, with citrus-driven acidity, a silky texture, and a long, precise finish.",
        "tasting_notes_th": "สีทองอ่อนสดใสพร้อมฟองอากาศที่เร็วและมีพลัง กลิ่นเผยให้เห็นบิสกิตและอัลมอนด์คั่ว พร้อมด้วยโน้ตส้มและดอกไม้สีขาว การเติมอากาศทำให้เกิดแร่ธาตุ พริกไทยขาว ผลไม้แห้ง และน้ำผึ้ง รสชาติมีชีวิตชีวาและบริสุทธิ์ ด้วยความเป็นกิดจากส้ม เนื้อสัมผัสเนียนนุ่ม และการจบที่ยาวนานและแม่นยำ",
        "pairing_en": "Best enjoyed with seafood (oysters, caviar), Parmesan or Pecorino, and as an aperitif for Champagne purists.",
        "pairing_th": "เหมาะที่สุดกับอาหารทะเล (หอยนางรม, คาเวียร์), พาร์เมซานหรือเปโครีโน และเป็นเครื่องดื่มเปิดมื้อสำหรับผู้ที่ชื่นชอบแชมเปญแท้จริง",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-002",
        "abv": "12.5%",
        "rating": "4.2",
        "price": "1,670 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Brut Prestige Champagne",
        "slug": "prestige-des-sacres-brut-prestige-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Fermented with a balanced dosage of 9-9.5 g/L<br>• Aged in cellars for 4 years, followed by 6 months in bottle post-disgorgement",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• หมักด้วยโดสาจที่สมดุล 9-9.5 กรัม/ลิตร<br>• หมักในห้องเก็บเป็นเวลา 4 ปี ตามด้วย 6 เดือนในขวดหลังการดีกอร์จมอง",
        "tasting_notes_en": "Pale yellow with green highlights and fine bubbles. Dominant citrus notes of grapefruit and tangerine, followed by floral hints and candied lemon. Fresh, mineral-driven palate with lingering acidity and a creamy texture.",
        "tasting_notes_th": "สีเหลืองอ่อนพร้อมไฮไลท์สีเขียวและฟองอากาศละเอียด โน้ตส้มโดดเด่นของเกรปฟรุตและส้มแมนดาริน ตามด้วยกลิ่นดอกไม้และมะนาวหวาน รสชาติสดชื่น ขับเคลื่อนด้วยแร่ธาตุ พร้อมความเป็นกิดที่คงอยู่และเนื้อสัมผัสครีมมี่",
        "pairing_en": "Ideal as an aperitif or paired with seafood (lobster, shrimp, shellfish), white meats, and mild cheeses like Brie and Camembert.",
        "pairing_th": "เหมาะเป็นเครื่องดื่มเปิดมื้อหรือจับคู่กับอาหารทะเล (กุ้งมังกร, กุ้ง, หอย), เนื้อสีขาว และชีสอ่อนๆ เช่น บรีและคามแบร์",
        "service_temperature": "16-18°C",
        "vintage": "Non vintage",
        "sku": "PRSA-001",
        "abv": "12.5%",
        "rating": "3.8",
        "price": "1,570 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>30&3 Extra Brut Champagne",
        "slug": "prestige-des-sacres-30-3-extra-brut-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "30% Meunier vinified in oak, 70% Chardonnay",
        "grape_varieties_th": "30% มูนิเยร์หมักในไม้โอ๊ค, 70% ชาร์ดอนเนย์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• Dosage: 3 g/L<br>• Aged over 5 years in cellars,<br>  followed by 6-12 months in bottle",
        "vinification_th": "• โดสาจ: 3 กรัม/ลิตร<br>• หมักอายุกว่า 5 ปีในห้องเก็บ<br>  ตามด้วย 6-12 เดือนในขวด",
        "tasting_notes_en": "A golden hue with lively bubbles. Aromas of cooked quince, honey, warm toast, and spices. The palate is rich yet mineral-driven, with cooked fruit and saline minerality leading to a persistent, cocoa-tinged finish.",
        "tasting_notes_th": "สีทองพร้อมฟองอากาศที่มีชีวิตชีวา กลิ่นหอมของควินซ์ปรุงสุก น้ำผึ้ง ขนมปังปิ้งอุ่น และเครื่องเทศ รสชาติเข้มข้นแต่ขับเคลื่อนด้วยแร่ธาตุ พร้อมผลไม้ปรุงสุกและแร่ธาตุเค็มนำไปสู่การจบที่ยาวนานและมีกลิ่นโกโก้",
        "pairing_en": "Pairs well with veal, pork, lamb, and creamy, earthy dishes.",
        "pairing_th": "เข้ากันดีกับเนื้อลูกวัว เนื้อหมู เนื้อแกะ และอาหารครีมมี่รสเอิร์ธี่",
        "service_temperature": "10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-006",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "2,230 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Cuvée Dynastie Blanc de Blancs Brut Champagne",
        "slug": "prestige-des-sacres-cuvee-dynastie-blanc-de-blancs-brut-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 8-9 g/L<br>• Aged for 4 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 8-9 กรัม/ลิตร<br>• หมักเป็นเวลา 4 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A pale yellow robe with green highlights and fine bubbles. Citrus notes of grapefruit and tangerine dominate, followed by floral hints and candied lemon. The palate is fresh and mineral-driven, with lingering acidity and a creamy texture.",
        "tasting_notes_th": "เสื้อคลุมสีเหลืองอ่อนพร้อมไฮไลท์สีเขียวและฟองอากาศละเอียด โน้ตส้มของเกรปฟรุตและส้มแมนดารินเด่นชัด ตามด้วยกลิ่นดอกไม้และมะนาวหวาน รสชาติสดชื่นและขับเคลื่อนด้วยแร่ธาตุ พร้อมความเป็นกิดที่คงอยู่และเนื้อสัมผัสครีมมี่",
        "pairing_en": "Best as an aperitif or with delicate seafood, sushi, and sashimi.",
        "pairing_th": "ดีที่สุดเป็นเครื่องดื่มเปิดมื้อหรือกับอาหารทะเลละเอียดอ่อน ซูชิ และซาชิมิ",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-003",
        "abv": "12.5%",
        "rating": "3.9",
        "price": "1,950 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Cuvée Grenat Millésime Champagne",
        "slug": "prestige-des-sacres-cuvee-grenat-millesime-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "50% Chardonnay, 50% Pinot Noir",
        "grape_varieties_th": "50% ชาร์ดอนเนย์, 50% ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 100% vintage 2015 wine<br>• Dosage: 9.9 g/L<br>• Aged for over 5 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์วินเทจ 2015 100%<br>• โดสาจ: 9.9 กรัม/ลิตร<br>• หมักเป็นเวลากว่า 5 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A golden-green hue with fine bubbles. Aromas of mirabelle plum, vetiver, pastry, and forest notes. The palate is rich and dense, with creamy honey flavors and a touch of zesty astringency, leading to a long, harmonious finish.",
        "tasting_notes_th": "สีทอง-เขียวพร้อมฟองอากาศละเอียด กลิ่นหอมของมิราเบลล์พลัม เวติเวอร์ เปสตรี้ และโน้ตป่าไผ่ รสชาติเข้มข้นและหนาแน่น พร้อมรสน้ำผึ้งครีมมี่และสัมผัสของความฝาดเปรี้ยวจี๊ด นำไปสู่การจบที่ยาวนานและกลมกลืน",
        "pairing_en": "Pairs well with creamy poultry dishes, veal, foie gras, and hearty stews.",
        "pairing_th": "เข้ากันดีกับอาหารสัตว์ปีกครีมมี่ เนื้อลูกวัว ฟัวกราส์ และสตูว์เข้มข้น",
        "service_temperature": "10°C",
        "vintage": "2015",
        "sku": "PRSA-004",
        "abv": "12.5%",
        "rating": "4.1",
        "price": "2,030 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Brut Rosé Champagne",
        "slug": "prestige-des-sacres-brut-rose-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "30% Chardonnay, 30% Pinot Noir, 40% Pinot Meunier with 15% vinified red",
        "grape_varieties_th": "30% ชาร์ดอนเนย์, 30% ปีโน นัวร์, 40% ปีโน มูนิเยร์ พร้อม 15% หมักแบบไวน์แดง",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 9-9.5 g/L<br>• Aged for 3 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 9-9.5 กรัม/ลิตร<br>• หมักเป็นเวลา 3 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A pale copper color with fine bubbles. The nose starts with wild berries and strawberries, evolving into caramel and butterscotch. The palate is round and juicy, featuring strawberry and kirsch cherry flavors with a fresh, tart finish.",
        "tasting_notes_th": "สีทองแดงอ่อนพร้อมฟองอากาศละเอียด กลิ่นเริ่มต้นด้วยเบอร์รี่ป่าและสตรอเบอร์รี่ พัฒนาไปสู่คาราเมลและบัตเตอร์สก็อตช์ รสชาติกลมกล่อมและฉ่ำ โดดเด่นด้วยรสสตรอเบอร์รี่และเชอร์รี่เคิร์ช พร้อมการจบที่สดชื่นและเปรี้ยว",
        "pairing_en": "Pairs beautifully with charcuterie, prosciutto, Serrano ham, and fruity or chocolate-based desserts.",
        "pairing_th": "เข้ากันอย่างสวยงามกับชาร์คูเตอรี่ โปรชูตโต แฮมเซร์ราโน และขนมหวานที่มีผลไม้หรือช็อกโกแลตเป็นส่วนประกอบ",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-005",
        "abv": "12.5%",
        "rating": "3.9",
        "price": "1,820 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Demi-Sec Champagne",
        "slug": "prestige-des-sacres-demi-sec-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 40 g/L<br>• Aged in cellars for 4 years,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 40 กรัม/ลิตร<br>• หมักในห้องเก็บเป็นเวลา 4 ปี<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "Aromas of shortbread, ripe mango, papaya, honey, and butterscotch. Sweet spices like cinnamon and nutmeg complement dried fruit notes. The palate is round and velvety, balancing acidity and effervescence with caramel and roasted nut flavors.",
        "tasting_notes_th": "กลิ่นหอมของช็อตเบรด มะม่วงสุก มะละกอ น้ำผึ้ง และบัตเตอร์สก็อตช์ เครื่องเทศหวานเช่นอบเชยและจันทน์เทศเสริมโน้ตผลไม้แห้ง รสชาติกลมกล่อมและนุ่มนวล สมดุลระหว่างความเป็นกิดและฟองอากาศ พร้อมรสคาราเมลและถั่วคั่ว",
        "pairing_en": "Perfect with blue cheeses (Roquefort, Stilton), foie gras, Asian sweet-and-sour dishes, and desserts.",
        "pairing_th": "เหมาะสมบูรณ์กับชีสบลู (โรคฟอร์ ส្ទิลตัน) ฟัวกราส์ อาหารเอเชียรสเปรี้ยวหวาน และขนมหวาน",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-007",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "1,650 + VAT"
      }
    ]
  },
  {
    "region_slug": "burgundy",
    "wines": [
      {
        "name": "Closerie des Alisiers<br>Vieilles Vignes Chablis 1er Cru",
        "slug": "closerie-des-alisiers-vieilles-vignes-chablis-1er-cru",
        "region_en": "Chablis, Burgundy",
        "region_th": "ชาบลิ, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Closerie des Alisiers is a boutique label that sources from old vines across the Chablis region. It focuses on showcasing terroir through minimal intervention and careful selection of plots with great aging potential.",
        "the_estate_th": "Closerie des Alisiers เป็นแบรนด์บูติกที่จัดหาจากเถาองุ่นแก่ทั่วภูมิภาคชาบลิ มุ่งเน้นการแสดงเทอร์รัวร์ผ่านการแทรกแซงเพียงเล็กน้อยและการคัดเลือกแปลงที่มีศักยภาพในการหมักที่ยอดเยี่ยม",
        "terroir_en": "• Soil: Kimmeridgian limestone rich in marine fossils<br>• Vineyard: 45-year-old vines from Premier Cru sites",
        "terroir_th": "• ดิน: หินปูนคิมเมอริเดียนอุดมไปด้วยฟอสซิลทางทะเล<br>• ไร่องุ่น: เถาองุ่นอายุ 45 ปีจากไซต์ Premier Cru",
        "vinification_en": "• Fermentation in stainless steel tanks<br>• Aged on lees for 10-12 months<br>• Minimal sulfur and no oak to preserve purity",
        "vinification_th": "• หมักในถังสแตนเลส<br>• หมักบนตะกอนเป็นเวลา 10-12 เดือน<br>• ใช้ซัลเฟอร์น้อยที่สุดและไม่ใช้ไม้โอ๊คเพื่อรักษาความบริสุทธิ์",
        "tasting_notes_en": "Fresh and intense on the nose, with citrus, flint, and white peach. The palate is crisp and mineral-driven, with chalky texture and long saline finish.",
        "tasting_notes_th": "สดชื่นและเข้มข้นในจมูก พร้อมส้ม หินไฟ และลูกพีชขาว รสชาติกรอบและขับเคลื่อนด้วยแร่ธาตุ พร้อมเนื้อสัมผัสชอล์กและการจบที่เค็มยาวนาน",
        "pairing_en": "Excellent with oysters, sea bass, grilled scallops, and goat cheese.",
        "pairing_th": "ยอดเยี่ยมกับหอยนางรม เซียเบส หอยเชลล์ย่าง และชีสแพะ",
        "service_temperature": "10-12°C",
        "vintage": "2021",
        "sku": "CLAL-001",
        "abv": "13%",
        "rating": "4.2",
        "price": "1,490 + VAT"
      },
      {
        "name": "Closerie des Alisiers<br>Petit Chablis",
        "slug": "closerie-des-alisiers-petit-chablis",
        "region_en": "Chablis, Burgundy",
        "region_th": "ชาบลิ, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Closerie des Alisiers is a small-scale négociant and micro-producer that selects grapes from top-quality vineyards in Chablis. The focus is on minimal intervention, clean vinification, and expressive terroir.",
        "the_estate_th": "Closerie des Alisiers เป็นผู้ค้าขนาดเล็กและผู้ผลิตไมโครที่คัดเลือกองุ่นจากไร่องุ่นคุณภาพสูงในชาบลิ เน้นการแทรกแซงเพียงเล็กน้อย การหมักที่สะอาด และเทอร์รัวร์ที่แสดงออก",
        "terroir_en": "• Soil: Portlandian limestone<br>• Vineyard: Young vines on high-altitude slopes",
        "terroir_th": "• ดิน: หินปูนพอร์ตแลนเดียน<br>• ไร่องุ่น: เถาองุ่นหนุ่มบนเนินเขาระดับสูง",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 6-8 months<br>• No oak used to preserve freshness",
        "vinification_th": "• หมักในสแตนเลส<br>• หมักบนตะกอนละเอียดเป็นเวลา 6-8 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่",
        "tasting_notes_en": "Lively and bright with aromas of green apple, citrus, and white flowers. The palate is zesty and clean with refreshing minerality and a crisp, dry finish.",
        "tasting_notes_th": "มีชีวิตชีวาและสดใสด้วยกลิ่นหอมของแอปเปิ้ลเขียว ส้ม และดอกไม้สีขาว รสชาติเปรี้ยวซ่าและสะอาด พร้อมแร่ธาตุที่สดชื่นและการจบที่กรอบและแห้ง",
        "pairing_en": "Great with shrimp cocktail, sushi, tempura, or fresh goat cheese.",
        "pairing_th": "ยอดเยี่ยมกับค็อกเทลกุ้ง ซูชิ เทมปุระ หรือชีสแพะสด",
        "service_temperature": "8-10°C",
        "vintage": "2022",
        "sku": "CLAL-002",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "990 + VAT"
      },
      {
        "name": "Closerie des Alisiers<br>Vieilles Vignes Marsannay",
        "slug": "closerie-des-alisiers-vieilles-vignes-marsannay",
        "region_en": "Marsannay, Côte de Nuits, Burgundy",
        "region_th": "มาร์ซันเน, โกต เดอ นูยต์, เบอร์กันดี",
        "grape_varieties_en": "100% Pinot Noir",
        "grape_varieties_th": "100% ปีโน นัวร์",
        "the_estate_en": "Closerie des Alisiers works closely with old-vine growers across Burgundy. In Marsannay, their focus is on expressive and structured Pinot Noir from some of the northernmost vineyards of the Côte de Nuits.",
        "the_estate_th": "Closerie des Alisiers ทำงานอย่างใกล้ชิดกับผู้ปลูกเถาองุ่นแก่ทั่วเบอร์กันดี ในมาร์ซันเน พวกเขามุ่งเน้นที่ปีโน นัวร์ที่แสดงออกและมีโครงสร้างจากไร่องุ่นที่อยู่ทางเหนือสุดของโกต เดอ นูยต์",
        "terroir_en": "• Soil: Clay-limestone with rocky subsoil<br>• Vineyard: Old vines (40+ years) from hillside plots",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนพร้อมชั้นดินล่างเป็นหิน<br>• ไร่องุ่น: เถาองุ่นแก่ (40+ ปี) จากแปลงบนเนินเขา",
        "vinification_en": "• Cold maceration before fermentation<br>• Fermented in stainless steel with indigenous yeasts<br>• Aged 12 months in French oak (20% new)",
        "vinification_th": "• แมซอเรชันเย็นก่อนการหมัก<br>• หมักในสแตนเลสสตีลด้วยยีสต์พื้นเมือง<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 20%)",
        "tasting_notes_en": "Aromas of dark cherry, red currant, and subtle earth. On the palate, it's juicy and structured with soft tannins and a mineral, peppery finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่เข้ม เรดเคอร์แรนต์ และดินเล็กน้อย ในปาก มีรสฉ่ำและมีโครงสร้าง พร้อมแทนนินนุ่มและการจบที่มีแร่ธาตุและเผ็ดร้อน",
        "pairing_en": "Perfect with roast chicken, pork tenderloin, duck confit, and firm cheeses.",
        "pairing_th": "เหมาะสมบูรณ์กับไก่ย่าง เนื้อหมูใน เป็ดคอนฟิต และชีสแข็ง",
        "service_temperature": "14-16°C",
        "vintage": "2021",
        "sku": "CLAL-003",
        "abv": "13%",
        "rating": "4.1",
        "price": "1,390 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Les Creuzettes Pouilly-Fuissé",
        "slug": "domaine-g-saumaize-les-creuzettes-pouilly-fuisse",
        "region_en": "Pouilly-Fuissé, Mâconnais, Burgundy",
        "region_th": "ปูยลีย์-ฟุยเซ, มาก็องเน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a small, family-run estate located in Vergisson, known for producing structured, age-worthy Chardonnay from exceptional terroirs in Pouilly-Fuissé. The Creuzettes plot is one of their prized lieux-dits, offering richness and elegance.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นขนาดเล็กที่ดำเนินการโดยครอบครัวที่ตั้งอยู่ในเวอร์ชิซง มีชื่อเสียงในการผลิตชาร์ดอนเนย์ที่มีโครงสร้างและมีอายุการเก็บจากเทอร์รัวร์ยอดเยี่ยมในปูยลีย์-ฟุยเซ แปลง Creuzettes เป็นหนึ่งใน lieux-dits ที่มีค่าของพวกเขา นำเสนอความเข้มข้นและความสง่างาม",
        "terroir_en": "• Soil: Clay-limestone with fossil-rich marl<br>• Altitude: 300 meters<br>• Vineyard: 40-year-old vines on southeast slopes",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนพร้อมมาร์ลที่อุดมไปด้วยฟอสซิล<br>• ระดับความสูง: 300 เมตร<br>• ไร่องุ่น: เถาองุ่นอายุ 40 ปีบนเนินทิศตะวันออกเฉียงใต้",
        "vinification_en": "• Fermentation in oak barrels (20% new)<br>• Aged 12 months on fine lees<br>• Light bâtonnage to enhance texture",
        "vinification_th": "• หมักในถังไม้โอ๊ค (ใหม่ 20%)<br>• หมักเป็นเวลา 12 เดือนบนตะกอนละเอียด<br>• บาโตนนาจเบาๆ เพื่อเสริมเนื้อสัมผัส",
        "tasting_notes_en": "Complex aromas of ripe pear, lemon peel, toasted almond, and white flowers. The palate is creamy yet precise, with vibrant acidity and a long mineral finish.",
        "tasting_notes_th": "กลิ่นหอมที่ซับซ้อนของลูกแพร์สุก เปลือกมะนาว อัลมอนด์คั่ว และดอกไม้สีขาว รสชาติครีมมี่แต่แม่นยำ พร้อมความเป็นกิดที่สดใสและการจบที่มีแร่ธาตุยาวนาน",
        "pairing_en": "Ideal with lobster, creamy poultry dishes, scallops, or aged Comté.",
        "pairing_th": "เหมาะสำหรับกุ้งมังกร อาหารสัตว์ปีกครีมมี่ หอยเชลล์ หรือ Comté ที่หมักแล้ว",
        "service_temperature": "10-12°C",
        "vintage": "2021",
        "sku": "SMPF-001",
        "abv": "13%",
        "rating": "4.3",
        "price": "1,750 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Mâcon-Davayé 'Les Belouzes'",
        "slug": "domaine-g-saumaize-macon-davaye-les-belouzes",
        "region_en": "Mâconnais, Burgundy",
        "region_th": "มาก็องเน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a traditional, family-operated estate in the village of Vergisson. They are known for crafting pure and terroir-driven Chardonnays in the Mâconnais region. 'Les Belouzes' comes from a high-quality lieu-dit in Davayé.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นแบบดั้งเดิมที่ดำเนินการโดยครอบครัวในหมู่บ้านเวอร์ชิซง พวกเขามีชื่อเสียงในการผลิตชาร์ดอนเนย์ที่บริสุทธิ์และขับเคลื่อนด้วยเทอร์รัวร์ในภูมิภาคมาก็องเน 'Les Belouzes' มาจาก lieu-dit คุณภาพสูงในดาวาเย",
        "terroir_en": "• Soil: Clay and limestone<br>• Exposure: Southeast-facing slope<br>• Vineyard: 35-year-old vines farmed sustainably",
        "terroir_th": "• ดิน: ดินเหนียวและหินปูน<br>• การหันหน้า: เนินเขาหันหน้าไปทางตะวันออกเฉียงใต้<br>• ไร่องุ่น: เถาองุ่นอายุ 35 ปีที่ปลูกอย่างยั่งยืน",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 10 months<br>• No oak to retain freshness and minerality",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• หมักบนตะกอนละเอียดเป็นเวลา 10 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่และแร่ธาตุ",
        "tasting_notes_en": "Bright and aromatic with notes of green apple, lemon zest, and crushed stones. Lively acidity and a clean, mineral finish make it highly refreshing.",
        "tasting_notes_th": "สดใสและหอมด้วยโน้ตของแอปเปิ้ลเขียว เปลือกมะนาวขูด และหินบด ความเป็นกิดที่มีชีวิตชีวาและการจบที่สะอาดมีแร่ธาตุทำให้สดชื่นอย่างมาก",
        "pairing_en": "Perfect with grilled prawns, chèvre salad, roast chicken, or steamed mussels.",
        "pairing_th": "เหมาะสมบูรณ์กับกุ้งย่าง สลัดเชฟร์ ไก่ย่าง หรือหอยแมลงภู่นึ่ง",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "SMMB-002",
        "abv": "13%",
        "rating": "4.1",
        "price": "990 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Bourgogne 'Les Prés Cousins'",
        "slug": "domaine-g-saumaize-bourgogne-les-pres-cousins",
        "region_en": "Burgundy",
        "region_th": "เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a family estate located in Vergisson in the Mâconnais. Their Bourgogne-level wines come from carefully tended parcels near the Pouilly-Fuissé area, offering exceptional quality for the appellation.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นครอบครัวที่ตั้งอยู่ในเวอร์ชิซงในมาก็องเน ไวน์ระดับเบอร์กองของพวกเขามาจากแปลงที่ได้รับการดูแลอย่างระมัดระวังใกล้กับพื้นที่ปูยลีย์-ฟุยเซ นำเสนอคุณภาพที่ยอดเยี่ยมสำหรับแอพเพลลาซง",
        "terroir_en": "• Soil: Clay-limestone<br>• Vineyard: 30-year-old vines located near Vergisson",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• ไร่องุ่น: เถาองุ่นอายุ 30 ปีที่ตั้งอยู่ใกล้เวอร์ชิซง",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 10 months<br>• No oak to preserve freshness and purity",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• หมักบนตะกอนละเอียดเป็นเวลา 10 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่และความบริสุทธิ์",
        "tasting_notes_en": "Fresh and floral with aromas of citrus, apple, and a hint of white peach. The palate is lively, round, and balanced with a crisp mineral finish.",
        "tasting_notes_th": "สดใหม่และหอมดอกไม้ด้วยกลิ่นหอมของส้ม แอปเปิ้ล และลูกพีชขาวเล็กน้อย รสชาติมีชีวิตชีวา กลม และสมดุล พร้อมการจบที่มีแร่ธาตุกรอบ",
        "pairing_en": "Ideal with grilled white fish, vegetable quiche, fresh cheeses, and seafood pasta.",
        "pairing_th": "เหมาะสำหรับปลาเนื้อขาวย่าง คิชผัก ชีสสด และพาสต้าซีฟู้ด",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "SMLP-003",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "890 + VAT"
      },
      {
        "name": "Domaine MaldantPauvelot<br>Bourgogne Chardonnay",
        "slug": "domaine-maldant-pauvelot-bourgogne-chardonnay",
        "region_en": "Côte de Beaune, Burgundy",
        "region_th": "โกต เดอ โบน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine Maldant Pauvelot is a family-run estate based in Chorey-lès-Beaune, known for producing elegant, terroir-driven wines across Burgundy. Their Bourgogne Chardonnay offers a refined expression of Côte de Beaune fruit with excellent value.",
        "the_estate_th": "Domaine Maldant Pauvelot เป็นไร่องุ่นที่ดำเนินการโดยครอบครัวที่ตั้งอยู่ในโชเร-เล-โบน มีชื่อเสียงในการผลิตไวน์ที่สง่างามและขับเคลื่อนด้วยเทอร์รัวร์ทั่วเบอร์กันดี ชาร์ดอนเนย์เบอร์กองของพวกเขานำเสนอการแสดงออกที่ประณีตของผลไม้โกต เดอ โบนด้วยคุณค่าที่ยอดเยี่ยม",
        "terroir_en": "• Soil: Limestone with clay deposits<br>• Vineyard: Multiple parcels near Chorey-lès-Beaune",
        "terroir_th": "• ดิน: หินปูนพร้อมตะกอนดินเหนียว<br>• ไร่องุ่น: แปลงหลายแปลงใกล้โชเร-เล-โบน",
        "vinification_en": "• Fermented in stainless steel vats<br>• Aged for 10 months on fine lees<br>• No oak used to preserve purity and freshness",
        "vinification_th": "• หมักในถังสแตนเลสสตีล<br>• หมักเป็นเวลา 10 เดือนบนตะกอนละเอียด<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความบริสุทธิ์และความสดใหม่",
        "tasting_notes_en": "Elegant and fresh with aromas of pear, citrus, and white flowers. The palate is supple and mineral-driven with a clean, persistent finish.",
        "tasting_notes_th": "สง่างามและสดใหม่ด้วยกลิ่นหอมของลูกแพร์ ส้ม และดอกไม้สีขาว รสชาตินุ่มนวลและขับเคลื่อนด้วยแร่ธาตุ พร้อมการจบที่สะอาดและยาวนาน",
        "pairing_en": "Excellent with grilled chicken, seafood pasta, vegetable terrine, and soft cheeses.",
        "pairing_th": "ยอดเยี่ยมกับไก่ย่าง พาสต้าซีฟู้ด เทอร์รีนผัก และชีสนุ่ม",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "MPBC-001",
        "abv": "13%",
        "rating": "4.1",
        "price": "980 + VAT"
      },
      {
        "name": "Domaine Maldant Pauvelot<br>Bourgogne Pinot Noir",
        "slug": "domaine-maldant-pauvelot-bourgogne-pinot-noir",
        "region_en": "Côte de Beaune, Burgundy",
        "region_th": "โกต เดอ โบน, เบอร์กันดี",
        "grape_varieties_en": "100% Pinot Noir",
        "grape_varieties_th": "100% ปีโน นัวร์",
        "the_estate_en": "Domaine Maldant Pauvelot is a historic family estate located in Chorey-lès-Beaune. With a focus on precision and tradition, they produce elegant red wines that reflect the finesse of Pinot Noir from the Côte de Beaune.",
        "the_estate_th": "Domaine Maldant Pauvelot เป็นไร่องุ่นครอบครัวที่มีประวัติศาสตร์ตั้งอยู่ในโชเร-เล-โบน ด้วยการมุ่งเน้นความแม่นยำและประเพณี พวกเขาผลิตไวน์แดงที่สง่างามซึ่งสะท้อนถึงความประณีตของปีโน นัวร์จากโกต เดอ โบน",
        "terroir_en": "• Soil: Clay-limestone<br>• Vineyard: Parcels near Chorey-lès-Beaune and surrounding villages",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• ไร่องุ่น: แปลงใกล้โชเร-เล-โบนและหมู่บ้านโดยรอบ",
        "vinification_en": "• Traditional fermentation in stainless steel<br>• Aged 10 months in oak barrels (15% new)<br>• Gentle extraction to preserve fruit and finesse",
        "vinification_th": "• การหมักแบบดั้งเดิมในสแตนเลสสตีล<br>• หมักเป็นเวลา 10 เดือนในถังไม้โอ๊ค (ใหม่ 15%)<br>• การสกัดอย่างอ่อนโยนเพื่อรักษาผลไม้และความประณีต",
        "tasting_notes_en": "Vibrant red cherry and raspberry aromas with light spice and floral notes. The palate is soft and juicy with silky tannins and a mineral finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่แดงและราสเบอร์รี่ที่สดใส พร้อมเครื่องเทศเบาและโน้ตดอกไม้ รสชาตินุ่มและฉ่ำ พร้อมแทนนินนุ่มนวลและการจบที่มีแร่ธาตุ",
        "pairing_en": "Great with roast duck, grilled salmon, mushroom dishes, and charcuterie.",
        "pairing_th": "ยอดเยี่ยมกับเป็ดย่าง แซลมอนย่าง อาหารเห็ด และชาร์คูเตอรี่",
        "service_temperature": "14-16°C",
        "vintage": "2022",
        "sku": "MPPN-002",
        "abv": "13%",
        "rating": "4.0",
        "price": "980 + VAT"
      }
    ]
  },
  {
    "region_slug": "bordeaux",
    "wines": [
      {
        "name": "Château Croizet-Bages<br>Pauillac Grand Cru Classé",
        "slug": "chateau-croizet-bages-pauillac-grand-cru-classe",
        "region_en": "Pauillac, Bordeaux",
        "region_th": "โปยยัก, บอร์โดซ์",
        "grape_varieties_en": "70% Cabernet Sauvignon, 30% Merlot",
        "grape_varieties_th": "70% คาเบอร์เนต์ โซวิญง, 30% เมอร์โล",
        "the_estate_en": "A Fifth Growth Grand Cru Classé since 1855, Château Croizet-Bages is located on the Bages plateau near Château Lynch-Bages. With 30 hectares of prime gravel soils, the estate produces classic Pauillac with aging potential and finesse.",
        "the_estate_th": "เป็น Fifth Growth Grand Cru Classé ตั้งแต่ปี 1855 Château Croizet-Bages ตั้งอยู่บนที่ราบสูง Bages ใกล้กับ Château Lynch-Bages ด้วยที่ดิน 30 เฮกตาร์ของดินกรวดชั้นดี ไร่องุ่นแห่งนี้ผลิตโปยยักคลาสสิกที่มีศักยภาพในการบ่มและความประณีต",
        "terroir_en": "• Soil: Deep gravel over limestone subsoil<br>• Sustainable farming practices",
        "terroir_th": "• ดิน: กรวดลึกบนชั้นดินล่างหินปูน<br>• การปฏิบัติการเกษตรแบบยั่งยืน",
        "vinification_en": "• Stainless steel fermentation<br>• 12-16 months in French oak (50% new)",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• 12-16 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 50%)",
        "tasting_notes_en": "Concentrated aromas of cassis, cedar, and tobacco. Full-bodied and structured, with firm tannins and a long, earthy finish.",
        "tasting_notes_th": "กลิ่นหอมเข้มข้นของแคสซิส ซีดาร์ และยาสูบ เต็มตัวและมีโครงสร้าง พร้อมแทนนินแข็งและการจบที่ยาวนานและเอิร์ธี่",
        "pairing_en": "Best with grilled ribeye, roast lamb, or hard cheeses.",
        "pairing_th": "ดีที่สุดกับริบอายย่าง เนื้อแกะย่าง หรือชีสแข็ง",
        "service_temperature": "16-18°C",
        "vintage": "2017",
        "sku": "CBPA-001",
        "abv": "13.5%",
        "rating": "4.2",
        "price": "2,290 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Pauillac",
        "slug": "la-croix-des-aubrais-pauillac",
        "region_en": "Pauillac, Bordeaux",
        "region_th": "โปยยัก, บอร์โดซ์",
        "grape_varieties_en": "60% Cabernet Sauvignon, 40% Merlot",
        "grape_varieties_th": "60% คาเบอร์เนต์ โซวิญง, 40% เมอร์โล",
        "the_estate_en": "La Croix des Aubrais is crafted by a renowned Pauillac château to offer an accessible and food-friendly expression of this prestigious appellation.",
        "the_estate_th": "La Croix des Aubrais ถูกสร้างสรรค์โดยชาโตโปยยักที่มีชื่อเสียง เพื่อมอบการแสดงออกที่เข้าถึงได้และเป็นมิตรกับอาหารของแอพเพลลาซองที่มีเกียรติแห่งนี้",
        "terroir_en": "• Soil: Gravel and clay-limestone<br>• Traditional left bank terroir",
        "terroir_th": "• ดิน: กรวดและดินเหนียว-หินปูน<br>• เทอร์รัวร์ฝั่งซ้ายแบบดั้งเดิม",
        "vinification_en": "• Fermentation in temperature-controlled vats<br>• 12 months in oak barrels",
        "vinification_th": "• การหมักในถังควบคุมอุณหภูมิ<br>• 12 เดือนในถังไม้โอ๊ค",
        "tasting_notes_en": "Blackcurrant, graphite, and cedar on the nose. Structured and elegant, with polished tannins and dark fruit on the finish.",
        "tasting_notes_th": "แบล็กเคอร์แรนต์ กราไฟต์ และซีดาร์ในจมูก มีโครงสร้างและสง่างาม พร้อมแทนนินที่ขัดเงาและผลไม้เข้มในการจบ",
        "pairing_en": "Beef stew, roast duck, and aged gouda.",
        "pairing_th": "สตูว์เนื้อ เป็ดย่าง และเก๋าดาหมัก",
        "service_temperature": "16-18°C",
        "vintage": "2019",
        "sku": "CDAP-002",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "1,290 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Saint-Julien",
        "slug": "la-croix-des-aubrais-saint-julien",
        "region_en": "Saint-Julien, Bordeaux",
        "region_th": "แซงต์-จูเลียง, บอร์โดซ์",
        "grape_varieties_en": "70% Cabernet Sauvignon, 25% Merlot, 5% Petit Verdot",
        "grape_varieties_th": "70% คาเบอร์เนต์ โซวิญง, 25% เมอร์โล, 5% เปอตี เวอร์โด",
        "the_estate_en": "Sourced from vineyards neighboring prestigious classified growths, this cuvée expresses the elegance and depth of Saint-Julien.",
        "the_estate_th": "ที่มาจากไร่องุ่นใกล้เคียงกับ classified growths ที่มีเกียรติ คิวเว่นี้แสดงออกถึงความสง่างามและความลึกของแซงต์-จูเลียง",
        "terroir_en": "• Soil: Deep gravel over limestone<br>• Classic Médoc terroir",
        "terroir_th": "• ดิน: กรวดลึกบนหินปูน<br>• เทอร์รัวร์เมดอกคลาสสิก",
        "vinification_en": "• Stainless steel vinification<br>• 12 months in oak (25% new)",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• 12 เดือนในไม้โอ๊ค (ใหม่ 25%)",
        "tasting_notes_en": "Elegant and refined with red plum, violet, and cedar aromas. Smooth tannins and excellent balance on the palate.",
        "tasting_notes_th": "สง่างามและประณีตด้วยกลิ่นหอมของพลัมแดง ไวโอเล็ต และซีดาร์ แทนนินเรียบและสมดุลยอดเยี่ยมในปาก",
        "pairing_en": "Lamb chops, mushroom risotto, and truffle cheese.",
        "pairing_th": "แลมบ์ช็อป ริซอตโต้เห็ด และชีสทรัฟเฟิล",
        "service_temperature": "16-18°C",
        "vintage": "2019",
        "sku": "CDAS-003",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,390 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Pomerol",
        "slug": "la-croix-des-aubrais-pomerol",
        "region_en": "Pomerol, Bordeaux",
        "region_th": "โปเมรอล, บอร์โดซ์",
        "grape_varieties_en": "90% Merlot, 10% Cabernet Franc",
        "grape_varieties_th": "90% เมอร์โล, 10% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "La Croix des Aubrais Pomerol comes from clay-rich vineyards that typify the right bank, delivering rich and velvety Merlot-driven wines.",
        "the_estate_th": "La Croix des Aubrais Pomerol มาจากไร่องุ่นที่อุดมไปด้วยดินเหนียวซึ่งเป็นตัวแทนของฝั่งขวา มอบไวน์ที่ขับเคลื่อนด้วยเมอร์โลที่เข้มข้นและนุ่มนวล",
        "terroir_en": "• Soil: Blue clay and gravel<br>• Right bank microclimate",
        "terroir_th": "• ดิน: ดินเหนียวสีฟ้าและกรวด<br>• ไมโครคลิเมตฝั่งขวา",
        "vinification_en": "• Vinified in concrete and stainless steel<br>• Aged 14 months in French oak barrels",
        "vinification_th": "• หมักในคอนกรีตและสแตนเลสสตีล<br>• หมักเป็นเวลา 14 เดือนในถังไม้โอ๊คฝรั่งเศส",
        "tasting_notes_en": "Plum, mocha, and blackberry aromas lead into a lush palate with round tannins and generous fruit.",
        "tasting_notes_th": "กลิ่นหอมของพลัม โมคา และแบล็กเบอร์รี่นำไปสู่รสชาติที่เข้มข้น พร้อมแทนนินกลมและผลไม้ที่เอื้อเฟื้อ",
        "pairing_en": "Duck breast, veal, mushroom-based dishes, and truffled pasta.",
        "pairing_th": "เนื้อเป็ดอก เนื้อลูกวัว อาหารที่มีเห็ดเป็นฐาน และพาสต้าทรัฟเฟิล",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "CDAP-004",
        "abv": "14%",
        "rating": "4.2",
        "price": "1,490 + VAT"
      },
      {
        "name": "Château Lilian Ladouys<br>Saint-Estèphe",
        "slug": "chateau-lilian-ladouys-saint-estephe",
        "region_en": "Saint-Estèphe, Bordeaux",
        "region_th": "แซงต์-เอสเตฟ, บอร์โดซ์",
        "grape_varieties_en": "55% Merlot, 40% Cabernet Sauvignon, 5% Petit Verdot",
        "grape_varieties_th": "55% เมอร์โล, 40% คาเบอร์เนต์ โซวิญง, 5% เปอตี เวอร์โด",
        "the_estate_en": "A Cru Bourgeois Exceptionnel with a long history, Château Lilian Ladouys combines richness and finesse with increasing critical acclaim in recent vintages.",
        "the_estate_th": "Cru Bourgeois Exceptionnel ที่มีประวัติศาสตร์ยาวนาน Château Lilian Ladouys ผสมผสานความเข้มข้นและความประณีต พร้อมการยกย่องจากนักวิจารณ์ที่เพิ่มขึ้นในวินเทจล่าสุด",
        "terroir_en": "• Soil: Gravel and clay<br>• Vines average 35 years of age",
        "terroir_th": "• ดิน: กรวดและดินเหนียว<br>• เถาองุ่นอายุเฉลี่ย 35 ปี",
        "vinification_en": "• Fermentation in stainless steel<br>• Aged 14 months in French oak (30% new)",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• หมักเป็นเวลา 14 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 30%)",
        "tasting_notes_en": "Ripe black fruits, tobacco, and spice on the nose. Broad and velvety with excellent structure and a mineral backbone.",
        "tasting_notes_th": "ผลไม้เข้มสุก ยาสูบ และเครื่องเทศในจมูก กว้างและนุ่มนวล พร้อมโครงสร้างที่ยอดเยี่ยมและแกนกระดูกแร่ธาตุ",
        "pairing_en": "Braised short ribs, roast beef, and hearty stews.",
        "pairing_th": "ซี่โครงสั้นต้ม เนื้อย่าง และสตูว์เข้มข้น",
        "service_temperature": "16-18°C",
        "vintage": "2018",
        "sku": "LLSE-005",
        "abv": "14%",
        "rating": "4.3",
        "price": "1,790 + VAT"
      },
      {
        "name": "Château de France<br>Pessac-Léognan",
        "slug": "chateau-de-france-pessac-leognan",
        "region_en": "Pessac-Léognan, Bordeaux",
        "region_th": "เปสซัก-เลโญง, บอร์โดซ์",
        "grape_varieties_en": "60% Cabernet Sauvignon, 40% Merlot",
        "grape_varieties_th": "60% คาเบอร์เนต์ โซวิญง, 40% เมอร์โล",
        "the_estate_en": "Château de France is a top-quality estate in Pessac-Léognan with a strong reputation for elegant, age-worthy wines with smoky complexity.",
        "the_estate_th": "Château de France เป็นไร่องุ่นคุณภาพสูงในเปสซัก-เลโญงที่มีชื่อเสียงอันแข็งแกร่งในด้านไวน์ที่สง่างาม มีอายุการเก็บ และมีความซับซ้อนแบบรมควัน",
        "terroir_en": "• Soil: Deep gravel over clay-limestone<br>• Located on one of the highest ridges in the appellation",
        "terroir_th": "• ดิน: กรวดลึกบนดินเหนียว-หินปูน<br>• ตั้งอยู่บนหนึ่งในสันเขาที่สูงที่สุดในแอพเพลลาซง",
        "vinification_en": "• Stainless steel vinification<br>• 12 months in French oak (30% new)",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 30%)",
        "tasting_notes_en": "Black cherry, graphite, and smoked herbs. The palate is precise with firm tannins and great length.",
        "tasting_notes_th": "เชอร์รี่เข้ม กราไฟต์ และสมุนไพรรมควัน รสชาติแม่นยำพร้อมแทนนินแข็งและความยาวที่ยอดเยี่ยม",
        "pairing_en": "Grilled lamb, duck confit, and mushroom-based dishes.",
        "pairing_th": "แกะย่าง เป็ดคอนฟิต และอาหารที่มีเห็ดเป็นฐาน",
        "service_temperature": "16-18°C",
        "vintage": "2019",
        "sku": "CFPL-006",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,650 + VAT"
      },
      {
        "name": "Château Capet Duverger<br>Saint-Émilion Grand Cru",
        "slug": "chateau-capet-duverger-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "90% Merlot, 10% Cabernet Franc",
        "grape_varieties_th": "90% เมอร์โล, 10% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Located on limestone plateaus just outside the village of Saint-Émilion, Capet Duverger is a Grand Cru estate that emphasizes elegance, balance, and terroir expression.",
        "the_estate_th": "ตั้งอยู่บนที่ราบสูงหินปูนนอกหมู่บ้านแซงต์-เอมิลิยง Capet Duverger เป็นไร่องุ่น Grand Cru ที่เน้นความสง่างาม สมดุล และการแสดงออกของเทอร์รัวร์",
        "terroir_en": "• Soil: Clay-limestone<br>• Vines averaging 35 years old",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• เถาองุ่นอายุเฉลี่ย 35 ปี",
        "vinification_en": "• Fermentation in concrete vats<br>• 12 months aging in French oak (25% new)",
        "vinification_th": "• การหมักในถังคอนกรีต<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 25%)",
        "tasting_notes_en": "Aromas of red cherry, violet, and spice. Supple texture with freshness and a long, floral finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่แดง ไวโอเล็ต และเครื่องเทศ เนื้อสัมผัสนุ่มนวลพร้อมความสดใหม่และการจบที่ยาวนานและหอมดอกไม้",
        "pairing_en": "Perfect with duck confit, grilled lamb, or mushroom ragù.",
        "pairing_th": "เหมาะสมบูรณ์กับเป็ดคอนฟิต แกะย่าง หรือราคูเห็ด",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "CDSE-007",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,290 + VAT"
      },
      {
        "name": "Château Tourbadon<br>Saint-Émilion Grand Cru",
        "slug": "chateau-tourbadon-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Château Tourbadon is a small Grand Cru estate producing concentrated, approachable wines from clay-limestone soils near the Saint-Émilion plateau.",
        "the_estate_th": "Château Tourbadon เป็นไร่องุ่น Grand Cru ขนาดเล็กที่ผลิตไวน์เข้มข้นและเข้าถึงได้ จากดินเหนียว-หินปูนใกล้ที่ราบสูงแซงต์-เอมิลิยง",
        "terroir_en": "• Soil: Clay-limestone and sandy loam<br>• Sustainably managed vineyards",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและดินร่วนทราย<br>• ไร่องุ่นที่จัดการอย่างยั่งยืน",
        "vinification_en": "• Fermented in stainless steel<br>• 12 months in oak barrels (20% new)",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• 12 เดือนในถังไม้โอ๊ค (ใหม่ 20%)",
        "tasting_notes_en": "Juicy red fruits, baking spices, and floral notes. Medium-bodied with soft tannins and a smooth finish.",
        "tasting_notes_th": "ผลไม้แดงฉ่ำ เครื่องเทศอบ และโน้ตดอกไม้ ตัวกลางพร้อมแทนนินนุ่มและการจบที่เรียบ",
        "pairing_en": "Pair with grilled meats, lentil stew, or roasted vegetables.",
        "pairing_th": "จับคู่กับเนื้อย่าง สตูว์ถั่วเลนทิล หรือผักย่าง",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "TBSE-008",
        "abv": "14%",
        "rating": "4.0",
        "price": "1,150 + VAT"
      },
      {
        "name": "Château Piney<br>Saint-Émilion Grand Cru",
        "slug": "chateau-piney-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Château Piney is a family-run Grand Cru estate producing traditional right bank wines with structure and depth, located just east of the village of Saint-Émilion.",
        "the_estate_th": "Château Piney เป็นไร่องุ่น Grand Cru ที่ดำเนินการโดยครอบครัว ผลิตไวน์ฝั่งขวาแบบดั้งเดิมที่มีโครงสร้างและความลึก ตั้งอยู่ทางตะวันออกของหมู่บ้านแซงต์-เอมิลิยง",
        "terroir_en": "• Soil: Clay-limestone<br>• Old vines over 35 years of age",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• เถาองุ่นแก่อายุกว่า 35 ปี",
        "vinification_en": "• Cold maceration and stainless steel fermentation<br>• Aged 12 months in oak (25% new)",
        "vinification_th": "• แมซอเรชันเย็นและการหมักในสแตนเลสสตีล<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊ค (ใหม่ 25%)",
        "tasting_notes_en": "Blackberry, plum, and spice aromas. Rich and smooth palate with firm tannins and earthy notes.",
        "tasting_notes_th": "กลิ่นหอมของแบล็กเบอร์รี่ พลัม และเครื่องเทศ รสชาติเข้มข้นและเรียบ พร้อมแทนนินแข็งและโน้ตเอิร์ธี่",
        "pairing_en": "Delicious with roast duck, beef bourguignon, or grilled eggplant.",
        "pairing_th": "อร่อยกับเป็ดย่าง บีฟ บูร์กินยง หรือมะเขือย่าง",
        "service_temperature": "16-18°C",
        "vintage": "2020",
        "sku": "PNSE-009",
        "abv": "14%",
        "rating": "4.1",
        "price": "1,290 + VAT"
      },
      {
        "name": "Galius<br>Saint-Émilion Grand Cru",
        "slug": "galius-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "100% Merlot",
        "grape_varieties_th": "100% เมอร์โล",
        "the_estate_en": "Galius is a boutique Grand Cru estate in Saint-Émilion. It produces Merlot-based wines with depth, balance, and great aging potential, showcasing the limestone terroirs of the region.",
        "the_estate_th": "Galius เป็นไร่องุ่น Grand Cru บูติกในแซงต์-เอมิลิยง ผลิตไวน์ที่มีฐานเป็นเมอร์โลพร้อมความลึก สมดุล และศักยภาพในการหมักอายุที่ยอดเยี่ยม แสดงให้เห็นถึงเทอร์รัวร์หินปูนของภูมิภาค",
        "terroir_en": "• Soil: Limestone plateau and clay-limestone slopes<br>• Sustainable viticulture",
        "terroir_th": "• ดิน: ที่ราบสูงหินปูนและเนินเขาดินเหนียว-หินปูน<br>• การปลูกองุ่นอย่างยั่งยืน",
        "vinification_en": "• Cold maceration<br>• Fermentation in stainless steel<br>• 12 months in French oak (30% new)",
        "vinification_th": "• แมซอเรชันเย็น<br>• การหมักในสแตนเลสสตีล<br>• 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 30%)",
        "tasting_notes_en": "Elegant and powerful with ripe plum, black cherry, and spicy oak notes. Smooth tannins and a long, mineral finish.",
        "tasting_notes_th": "สง่างามและทรงพลังด้วยพลัมสุก เชอร์รี่เข้ม และโน้ตไม้โอ๊คเผ็ด แทนนินเรียบและการจบที่ยาวนาน เต็มไปด้วยแร่ธาตุ",
        "pairing_en": "Perfect with roast duck, truffle risotto, or aged Comté.",
        "pairing_th": "เหมาะสมบูรณ์กับเป็ดย่าง ริซอตโต้ทรัฟเฟิล หรือคองเต้อายุ",
        "service_temperature": "16-18°C",
        "vintage": "2020",
        "sku": "GAL-010",
        "abv": "14%",
        "rating": "4.2",
        "price": "1,450 + VAT"
      },
      {
        "name": "Château Rocher Gardat<br>Montagne Saint-Émilion",
        "slug": "chateau-rocher-gardat-montagne-saint-emilion",
        "region_en": "Montagne Saint-Émilion, Bordeaux",
        "region_th": "มงตาญแซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Located in the Montagne satellite of Saint-Émilion, Château Rocher Gardat is a traditional estate producing supple and approachable wines from clay-limestone soils.",
        "the_estate_th": "ตั้งอยู่ในดาวเทียมมงตาญของแซงต์-เอมิลิยง Château Rocher Gardat เป็นไร่องุ่นแบบดั้งเดิมที่ผลิตไวน์ที่นุ่มนวลและเข้าถึงได้จากดินเหนียว-หินปูน",
        "terroir_en": "• Soil: Clay and limestone<br>• Vines average 30 years of age",
        "terroir_th": "• ดิน: ดินเหนียวและหินปูน<br>• เถาองุ่นอายุเฉลี่ย 30 ปี",
        "vinification_en": "• Vinified in stainless steel<br>• 12 months in oak barrels",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• 12 เดือนในถังไม้โอ๊ค",
        "tasting_notes_en": "Bright red fruits, hints of tobacco and spice. Smooth and rounded palate with a touch of earthiness.",
        "tasting_notes_th": "ผลไม้แดงสดใส กลิ่นยาสูบและเครื่องเทศ รสชาติเรียบและกลมกล่อม พร้อมสัมผัสของเอิร์ธีเนส",
        "pairing_en": "Excellent with charcuterie, grilled pork, and soft cheeses.",
        "pairing_th": "ยอดเยี่ยมกับชาร์คูเตอรี่ เนื้อหมูย่าง และชีสนุ่ม",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "RGMS-011",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "950 + VAT"
      },
      {
        "name": "Château Haut Grelot<br>Blaye Côtes de Bordeaux Blanc",
        "slug": "chateau-haut-grelot-blaye-cotes-de-bordeaux-blanc",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "70% Sauvignon Blanc, 30% Sémillon",
        "grape_varieties_th": "70% โซวิญง บลัง, 30% เซมิยง",
        "the_estate_en": "Château Haut Grelot is a family estate located on clay-limestone hillsides near the Gironde estuary. Their white wines are fresh, expressive, and ideal for warm climates.",
        "the_estate_th": "Château Haut Grelot เป็นไร่องุ่นครอบครัวที่ตั้งอยู่บนเนินเขาดินเหนียว-หินปูนใกล้ปากแม่น้ำจิรงด์ ไวน์ขาวของพวกเขาสดใหม่ แสดงออก และเหมาะสำหรับสภาพอากาศอุ่น",
        "terroir_en": "• Soil: Clay-limestone<br>• Cool microclimate near the river",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• ไมโครคลิเมตเย็นใกล้แม่น้ำ",
        "vinification_en": "• Fermented in stainless steel at low temperatures<br>• Aged on fine lees",
        "vinification_th": "• หมักในสแตนเลสสตีลที่อุณหภูมิต่ำ<br>• หมักบนตะกอนละเอียด",
        "tasting_notes_en": "Zesty citrus and tropical fruit notes with a crisp, mineral finish. Vibrant and aromatic.",
        "tasting_notes_th": "โน้ตส้มและผลไม้เขตร้อนที่มีรสชาติ พร้อมการจบที่คมและเต็มไปด้วยแร่ธาตุ มีชีวิตชีวาและหอม",
        "pairing_en": "Ideal with grilled prawns, goat cheese salad, and ceviche.",
        "pairing_th": "เหมาะกับกุ้งย่าง สลัดชีสแพะ และเซวิเช่",
        "service_temperature": "8-10°C",
        "vintage": "2022",
        "sku": "HGBB-012",
        "abv": "12.5%",
        "rating": "4.1",
        "price": "690 + VAT"
      },
      {
        "name": "Château Haut Grelot<br>Blaye Côtes de Bordeaux Rouge",
        "slug": "chateau-haut-grelot-blaye-cotes-de-bordeaux-rouge",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "60% Merlot, 40% Cabernet Sauvignon",
        "grape_varieties_th": "60% เมอร์โล, 40% คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "A benchmark producer in Blaye, Château Haut Grelot delivers generous and fruit-forward red wines with finesse and balance.",
        "the_estate_th": "ผู้ผลิตต้นแบบในเบลย์ Château Haut Grelot มอบไวน์แดงที่เอื้อเฟื้อและนำโดยผลไม้ พร้อมความประณีตและสมดุล",
        "terroir_en": "• Soil: Sandy gravel with clay-limestone<br>• Gentle south-facing slopes",
        "terroir_th": "• ดิน: กรวดทรายกับดินเหนียว-หินปูน<br>• เนินเขาหันหน้าไปทางใต้อย่างอ่อนโยน",
        "vinification_en": "• Traditional vinification in stainless steel<br>• Aged partially in oak barrels",
        "vinification_th": "• การหมักแบบดั้งเดิมในสแตนเลสสตีล<br>• หมักบางส่วนในถังไม้โอ๊ค",
        "tasting_notes_en": "Blackberry, plum, and vanilla on the nose. Smooth texture with round tannins and good freshness.",
        "tasting_notes_th": "แบล็กเบอร์รี่ พลัม และวานิลลาในจมูก เนื้อสัมผัสเรียบพร้อมแทนนินกลมและความสดใหม่ที่ดี",
        "pairing_en": "Perfect for grilled meats, sausages, and roast chicken.",
        "pairing_th": "เหมาะสมบูรณ์สำหรับเนื้อย่าง ไส้กรอก และไก่ย่าง",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "HGBR-013",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "690 + VAT"
      },
      {
        "name": "Château Haut-Bourcier<br>Blaye Côtes de Bordeaux",
        "slug": "chateau-haut-bourcier-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Château Haut-Bourcier is a family estate crafting modern, fruit-driven Bordeaux wines. They emphasize clean, ripe fruit and freshness in their approachable blends.",
        "the_estate_th": "Château Haut-Bourcier เป็นไร่องุ่นครอบครัวที่สร้างไวน์บอร์โดซ์สมัยใหม่ที่ขับเคลื่อนด้วยผลไม้ พวกเขาเน้นผลไม้สุกสะอาดและความสดใหม่ในการผสมผสานที่เข้าถึงได้",
        "terroir_en": "• Soil: Clay-limestone and sandy gravel<br>• Well-drained vineyards",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและกรวดทราย<br>• ไร่องุ่นที่ระบายน้ำดี",
        "vinification_en": "• Vinification in temperature-controlled vats<br>• Aged in stainless steel and part in oak",
        "vinification_th": "• การหมักในถังควบคุมอุณหภูมิ<br>• หมักในสแตนเลสสตีลและส่วนหนึ่งในไม้โอ๊ค",
        "tasting_notes_en": "Juicy red fruits and floral notes. Medium-bodied with silky tannins and balanced acidity.",
        "tasting_notes_th": "ผลไม้แดงฉ่ำและโน้ตดอกไม้ ตัวกลางพร้อมแทนนินไหมและความเป็นกิดที่สมดุล",
        "pairing_en": "Serve with pasta dishes, charcuterie, or grilled vegetables.",
        "pairing_th": "เสิร์ฟกับอาหารพาสต้า ชาร์คูเตอรี่ หรือผักย่าง",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "HBBR-014",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "750 + VAT"
      },
      {
        "name": "Château Terre Blanque<br>Blaye Côtes de Bordeaux",
        "slug": "chateau-terre-blanque-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "Château Terre Blanque is a small estate in Blaye known for producing value-driven wines that reflect the generous, fruit-forward style of the region.",
        "the_estate_th": "Château Terre Blanque เป็นไร่องุ่นขนาดเล็กในเบลย์ที่ขึ้นชื่อในการผลิตไวน์ที่ขับเคลื่อนด้วยคุณค่าซึ่งสะท้อนถึงสไตล์ที่เอื้อเฟื้อและนำโดยผลไม้ของภูมิภาค",
        "terroir_en": "• Soil: Limestone-rich clay<br>• Hilly terrain with excellent sun exposure",
        "terroir_th": "• ดิน: ดินเหนียวที่อุดมไปด้วยหินปูน<br>• ภูมิประเทศเป็นเนินเขาพร้อมการรับแสงแดดที่ยอดเยี่ยม",
        "vinification_en": "• Traditional fermentation in stainless steel<br>• Aged briefly in oak for structure",
        "vinification_th": "• การหมักแบบดั้งเดิมในสแตนเลสสตีล<br>• หมักในไม้โอ๊คช่วงสั้นเพื่อโครงสร้าง",
        "tasting_notes_en": "Ripe red fruit, spice, and floral hints. Medium-bodied with round tannins and a smooth finish.",
        "tasting_notes_th": "ผลไม้แดงสุก เครื่องเทศ และกลิ่นดอกไม้ ตัวกลางพร้อมแทนนินกลมและการจบที่เรียบ",
        "pairing_en": "Good with grilled pork, roasted vegetables, and lentil stew.",
        "pairing_th": "ดีกับเนื้อหมูย่าง ผักย่าง และสตูว์ถั่วเลนทิล",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "TBBR-015",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "690 + VAT"
      },
      {
        "name": "Château Haut-Lalande<br>Grand Vin Blaye Côtes de Bordeaux",
        "slug": "chateau-haut-lalande-grand-vin-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Sauvignon",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "Château Haut-Lalande is a small estate producing high-quality wines from hillside vineyards. Their Grand Vin is their flagship cuvée, emphasizing structure and finesse.",
        "the_estate_th": "Château Haut-Lalande เป็นไร่องุ่นขนาดเล็กที่ผลิตไวน์คุณภาพสูงจากไร่องุ่นบนเนินเขา Grand Vin ของพวกเขาเป็นคิวเว่เรือธงที่เน้นโครงสร้างและความประณีต",
        "terroir_en": "• Soil: Clay-limestone<br>• Vines on well-exposed slopes",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• เถาองุ่นบนเนินเขาที่รับแสงดี",
        "vinification_en": "• Traditional vinification<br>• Aged in oak barrels for 12 months",
        "vinification_th": "• การหมักแบบดั้งเดิม<br>• หมักในถังไม้โอ๊คเป็นเวลา 12 เดือน",
        "tasting_notes_en": "Ripe red fruits with hints of vanilla and spice. Medium-bodied with velvety tannins and long finish.",
        "tasting_notes_th": "ผลไม้แดงสุกพร้อมกลิ่นวานิลลาและเครื่องเทศ ตัวกลางพร้อมแทนนินนุ่มนวลและการจบที่ยาวนาน",
        "pairing_en": "Great with lamb, mushroom-based dishes, or aged cheeses.",
        "pairing_th": "ยอดเยี่ยมกับแกะ อาหารที่มีเห็ดเป็นฐาน หรือชีสอายุ",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "HLLB-016",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "850 + VAT"
      },
      {
        "name": "Château La Roche Bazin<br>Blaye Côtes de Bordeaux",
        "slug": "chateau-la-roche-bazin-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "A traditional estate focused on sustainable viticulture and producing balanced red Bordeaux with freshness and purity of fruit.",
        "the_estate_th": "ไร่องุ่นแบบดั้งเดิมที่มุ่งเน้นการปลูกองุ่นอย่างยั่งยืนและผลิตบอร์โดซ์แดงที่สมดุล พร้อมความสดใหม่และความบริสุทธิ์ของผลไม้",
        "terroir_en": "• Soil: Limestone-rich clay<br>• Slightly elevated vineyards",
        "terroir_th": "• ดิน: ดินเหนียวที่อุดมไปด้วยหินปูน<br>• ไร่องุ่นที่สูงขึ้นเล็กน้อย",
        "vinification_en": "• Stainless steel fermentation<br>• Aged 6 months in oak",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• หมักเป็นเวลา 6 เดือนในไม้โอ๊ค",
        "tasting_notes_en": "Notes of blackberry, violet, and cedar. Juicy and approachable with a silky finish.",
        "tasting_notes_th": "โน้ตของแบล็กเบอร์รี่ ไวโอเล็ต และซีดาร์ ฉ่ำและเข้าถึงได้พร้อมการจบที่เนียนนุ่ม",
        "pairing_en": "Pair with grilled chicken, beef burgers, or vegetarian lasagna.",
        "pairing_th": "จับคู่กับไก่ย่าง เบอร์เกอร์เนื้อ หรือลาซานญ่ามังสวิรัติ",
        "service_temperature": "16°C",
        "vintage": "2021",
        "sku": "LRBB-017",
        "abv": "13%",
        "rating": "4.0",
        "price": "650 + VAT"
      },
      {
        "name": "Château Haut Prieur<br>Blaye Côtes de Bordeaux",
        "slug": "chateau-haut-prieur-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "Château Haut Prieur is known for producing round and fruit-forward wines from well-drained soils. The wines are aged to develop complexity and smooth tannins.",
        "the_estate_th": "Château Haut Prieur ขึ้นชื่อในการผลิตไวน์ที่กลมกล่อมและนำโดยผลไม้จากดินที่ระบายน้ำดี ไวน์ได้รับการหมักอายุเพื่อพัฒนาความซับซ้อนและแทนนินที่เรียบ",
        "terroir_en": "• Soil: Clay and gravel<br>• Hillside vineyards",
        "terroir_th": "• ดิน: ดินเหนียวและกรวด<br>• ไร่องุ่นบนเนินเขา",
        "vinification_en": "• Stainless steel vinification<br>• Aged 6-8 months in oak",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• หมักเป็นเวลา 6-8 เดือนในไม้โอ๊ค",
        "tasting_notes_en": "Bright cherry, blackberry, and spice. Medium-bodied and smooth on the finish.",
        "tasting_notes_th": "เชอร์รี่สดใส แบล็กเบอร์รี่ และเครื่องเทศ ตัวกลางและเรียบในการจบ",
        "pairing_en": "Best with grilled meats, lentils, or mushroom risotto.",
        "pairing_th": "ดีที่สุดกับเนื้อย่าง ถั่วเลนทิล หรือริซอตโต้เห็ด",
        "service_temperature": "16-17°C",
        "vintage": "2020",
        "sku": "HPRB-018",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "690 + VAT"
      },
      {
        "name": "Château Beaumont<br>Les Pierrières Blaye Côtes de Bordeaux",
        "slug": "chateau-beaumont-les-pierrieres-blaye-cotes-de-bordeaux",
        "region_en": "Blaye Côtes de Bordeaux",
        "region_th": "เบลย์ โคต เดอ บอร์โดซ์",
        "grape_varieties_en": "80% Merlot, 20% Cabernet Sauvignon",
        "grape_varieties_th": "80% เมอร์โล, 20% คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "Beaumont's Les Pierrières cuvée comes from specific gravelly plots, giving the wine complexity and good aging potential.",
        "the_estate_th": "คิวเว่ Les Pierrières ของ Beaumont มาจากแปลงกรวดเฉพาะ ให้ความซับซ้อนของไวน์และศักยภาพในการหมักอายุที่ดี",
        "terroir_en": "• Soil: Gravel and clay<br>• South-facing slopes",
        "terroir_th": "• ดิน: กรวดและดินเหนียว<br>• เนินเขาหันหน้าไปทางใต้",
        "vinification_en": "• Fermentation in temperature-controlled vats<br>• Aging in oak barrels",
        "vinification_th": "• การหมักในถังควบคุมอุณหภูมิ<br>• การหมักอายุในถังไม้โอ๊ค",
        "tasting_notes_en": "Complex nose of black fruit and spice. Dense palate with firm tannins and good freshness.",
        "tasting_notes_th": "กลิ่นซับซ้อนของผลไม้เข้มและเครื่องเทศ รสชาติหนาแน่นพร้อมแทนนินแข็งและความสดใหม่ที่ดี",
        "pairing_en": "Pairs well with lamb, game, and firm cheeses.",
        "pairing_th": "เข้ากันดีกับแกะ เนื้อป่า และชีสแข็ง",
        "service_temperature": "17-18°C",
        "vintage": "2020",
        "sku": "BLPB-019",
        "abv": "13.5%",
        "rating": "4.2",
        "price": "850 + VAT"
      },
      {
        "name": "Vignobles de Paloumey<br>Ailes de Paloumey Haut-Médoc",
        "slug": "vignobles-de-paloumey-ailes-de-paloumey-haut-medoc",
        "region_en": "Haut-Médoc, Bordeaux",
        "region_th": "โอต์-เมดอก, บอร์โดซ์",
        "grape_varieties_en": "50% Merlot, 45% Cabernet Sauvignon, 5% Petit Verdot",
        "grape_varieties_th": "50% เมอร์โล, 45% คาเบอร์เนต์ โซวิญง, 5% เปอตี เวอร์โด",
        "the_estate_en": "A second wine of Château Paloumey, located near La Lagune and Cantemerle. Ailes de Paloumey is a refined Haut-Médoc with finesse and fruit.",
        "the_estate_th": "ไวน์ที่สองของ Château Paloumey ตั้งอยู่ใกล้ La Lagune และ Cantemerle Ailes de Paloumey เป็นโอต์-เมดอกที่ประณีตพร้อมความละเอียดและผลไม้",
        "terroir_en": "• Soil: Garonne gravel and clay-limestone<br>• Certified organic",
        "terroir_th": "• ดิน: กรวดการอนน์และดินเหนียว-หินปูน<br>• ได้รับการรับรองออร์แกนิก",
        "vinification_en": "• Gravity-fed vinification<br>• 12 months in oak barrels (30% new)",
        "vinification_th": "• การหมักแบบใช้แรงโน้มถ่วง<br>• 12 เดือนในถังไม้โอ๊ค (ใหม่ 30%)",
        "tasting_notes_en": "Blackcurrant, violet, and cedar aromas. Polished tannins and elegant structure.",
        "tasting_notes_th": "กลิ่นหอมของแบล็กเคอร์แรนท์ ไวโอเล็ต และซีดาร์ แทนนินขัดเงาและโครงสร้างที่สง่างาม",
        "pairing_en": "Roast duck, steak, and aged cheese.",
        "pairing_th": "เป็ดย่าง สเต็ก และชีสอายุ",
        "service_temperature": "17°C",
        "vintage": "2019",
        "sku": "APHM-020",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "990 + VAT"
      },
      {
        "name": "Maison Bouey<br>Château La France Delhomme Médoc",
        "slug": "maison-bouey-chateau-la-france-delhomme-medoc",
        "region_en": "Médoc, Bordeaux",
        "region_th": "เมดอก, บอร์โดซ์",
        "grape_varieties_en": "Cabernet Sauvignon, Merlot",
        "grape_varieties_th": "คาเบอร์เนต์ โซวิญง, เมอร์โล",
        "the_estate_en": "Maison Bouey is one of Bordeaux's leading family-owned négociants. Their Médoc wines offer excellent value and reflect traditional left bank style.",
        "the_estate_th": "Maison Bouey เป็นหนึ่งในเนโกซียงต์ที่เป็นเจ้าของครอบครัวชั้นนำของบอร์โดซ์ ไวน์เมดอกของพวกเขามอบคุณค่าที่ยอดเยี่ยมและสะท้อนถึงสไตล์ฝั่งซ้ายแบบดั้งเดิม",
        "terroir_en": "• Soil: Gravel and clay<br>• Left bank microclimate",
        "terroir_th": "• ดิน: กรวดและดินเหนียว<br>• ไมโครคลิเมตฝั่งซ้าย",
        "vinification_en": "• Stainless steel fermentation<br>• Partially aged in oak barrels",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• หมักอายุบางส่วนในถังไม้โอ๊ค",
        "tasting_notes_en": "Cassis, graphite, and pepper. Full-bodied with classic Médoc tannins.",
        "tasting_notes_th": "แคสซิส กราไฟต์ และพริกไทย เต็มตัวพร้อมแทนนินเมดอกคลาสสิก",
        "pairing_en": "Beef stew, duck confit, or mushroom-based dishes.",
        "pairing_th": "สตูว์เนื้อ เป็ดคอนฟิต หรืออาหารที่มีเห็ดเป็นฐาน",
        "service_temperature": "17-18°C",
        "vintage": "2020",
        "sku": "FDME-021",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "790 + VAT"
      },
      {
        "name": "Michel Morin<br>Médoc",
        "slug": "michel-morin-medoc",
        "region_en": "Médoc, Bordeaux",
        "region_th": "เมดอก, บอร์โดซ์",
        "grape_varieties_en": "Cabernet Sauvignon, Merlot",
        "grape_varieties_th": "คาเบอร์เนต์ โซวิญง, เมอร์โล",
        "the_estate_en": "Michel Morin crafts traditional Médoc wines from gravelly vineyards. The wines are bold, structured, and ideal with hearty cuisine.",
        "the_estate_th": "Michel Morin สร้างไวน์เมดอกแบบดั้งเดิมจากไร่องุ่นกรวด ไวน์มีความกล้าหาญ มีโครงสร้าง และเหมาะกับอาหารเข้มข้น",
        "terroir_en": "• Soil: Gravel and clay<br>• Sustainable viticulture",
        "terroir_th": "• ดิน: กรวดและดินเหนียว<br>• การปลูกองุ่นอย่างยั่งยืน",
        "vinification_en": "• Fermentation in stainless steel<br>• Oak aging for 10-12 months",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• การหมักอายุในไม้โอ๊คเป็นเวลา 10-12 เดือน",
        "tasting_notes_en": "Aromas of dark berries, tobacco, and oak. Rich, structured, and long finish.",
        "tasting_notes_th": "กลิ่นหอมของเบอร์รี่เข้ม ยาสูบ และไม้โอ๊ค เข้มข้น มีโครงสร้าง และการจบที่ยาวนาน",
        "pairing_en": "Great with grilled meats, stews, or hard cheeses.",
        "pairing_th": "ยอดเยี่ยมกับเนื้อย่าง สตูว์ หรือชีสแข็ง",
        "service_temperature": "17-18°C",
        "vintage": "2020",
        "sku": "MOME-022",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "750 + VAT"
      },
      {
        "name": "Les Vignerons Réunis de Monségur<br>Cuvée Nokat Élevé Fût de Chêne Bordeaux",
        "slug": "les-vignerons-reunis-de-monsegur-cuvee-nokat-eleve-fut-de-chene-bordeaux",
        "region_en": "Bordeaux",
        "region_th": "บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "Produced by a cooperative of quality-focused growers in Monségur, this oak-aged Bordeaux delivers richness and complexity at excellent value.",
        "the_estate_th": "ผลิตโดยสหกรณ์ของผู้ปลูกที่มุ่งเน้นคุณภาพในมงเซกูร์ บอร์โดซ์ที่หมักในไม้โอ๊คนี้มอบความเข้มข้นและความซับซ้อนในราคาที่ยอดเยี่ยม",
        "terroir_en": "• Soil: Clay-limestone and sandy gravel<br>• Vineyard altitude: 80-100m",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและกรวดทราย<br>• ความสูงของไร่องุ่น: 80-100 เมตร",
        "vinification_en": "• Traditional vinification<br>• Aged in French oak barrels",
        "vinification_th": "• การหมักแบบดั้งเดิม<br>• หมักในถังไม้โอ๊คฝรั่งเศส",
        "tasting_notes_en": "Ripe cherry, spice, and toast. Velvety mouthfeel with soft tannins.",
        "tasting_notes_th": "เชอร์รี่สุก เครื่องเทศ และขนมปังปิ้ง ความรู้สึกในปากนุ่มนวลพร้อมแทนนินนุ่ม",
        "pairing_en": "Barbecue, lasagna, or roast pork.",
        "pairing_th": "บาร์บีคิว ลาซานญ่า หรือเนื้อหมูย่าง",
        "service_temperature": "16-17°C",
        "vintage": "2021",
        "sku": "NOKF-023",
        "abv": "13%",
        "rating": "4.0",
        "price": "690 + VAT"
      },
      {
        "name": "Les Vignerons Réunis de Monségur<br>Cuvée Nokat Bordeaux",
        "slug": "les-vignerons-reunis-de-monsegur-cuvee-nokat-bordeaux",
        "region_en": "Bordeaux",
        "region_th": "บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "The unoaked version of Cuvée Nokat offers a fresher, more fruit-forward Bordeaux ideal for casual drinking.",
        "the_estate_th": "เวอร์ชันไม่ใช้ไม้โอ๊คของ Cuvée Nokat เสนอบอร์โดซ์ที่สดใหม่กว่าและนำโดยผลไม้มากขึ้น เหมาะสำหรับการดื่มแบบสบายๆ",
        "terroir_en": "• Soil: Clay-limestone and sandy loam<br>• Gentle slopes near Monségur",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและดินร่วนทราย<br>• เนินเขาอ่อนโยนใกล้มงเซกูร์",
        "vinification_en": "• Vinified in stainless steel<br>• No oak aging",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• ไม่มีการหมักอายุในไม้โอ๊ค",
        "tasting_notes_en": "Fresh red berries and a floral hint. Easy-drinking, smooth, and bright.",
        "tasting_notes_th": "เบอร์รี่แดงสดและกลิ่นดอกไม้ ดื่มง่าย เรียบ และสดใส",
        "pairing_en": "Perfect for pizza, pasta, and grilled vegetables.",
        "pairing_th": "เหมาะสมบูรณ์สำหรับพิซซ่า พาสต้า และผักย่าง",
        "service_temperature": "15-16°C",
        "vintage": "2022",
        "sku": "NOKB-024",
        "abv": "13%",
        "rating": "3.9",
        "price": "590 + VAT"
      },
      {
        "name": "Les Parcelles Delatour<br>Bordeaux Blanc",
        "slug": "les-parcelles-delatour-bordeaux-blanc",
        "region_en": "Bordeaux",
        "region_th": "บอร์โดซ์",
        "grape_varieties_en": "Sauvignon Blanc, Sémillon",
        "grape_varieties_th": "โซวิญง บลัง, เซมิยง",
        "the_estate_en": "Delatour's white Bordeaux is crisp and fresh, offering aromatic intensity and balance from select vineyard parcels.",
        "the_estate_th": "บอร์โดซ์ขาวของ Delatour คมและสดใหม่ เสนอความเข้มข้นของกลิ่นหอมและสมดุลจากแปลงไร่องุ่นที่คัดสรร",
        "terroir_en": "• Soil: Limestone and gravel<br>• Cool climate sites",
        "terroir_th": "• ดิน: หินปูนและกรวด<br>• ไซต์ที่มีสภาพอากาศเย็น",
        "vinification_en": "• Stainless steel vinification<br>• Aged on lees for texture",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• หมักบนตะกอนเพื่อเนื้อสัมผัส",
        "tasting_notes_en": "Citrus, white flowers, and passionfruit. Fresh, mineral finish.",
        "tasting_notes_th": "ส้ม ดอกไม้สีขาว และเสาวรส การจบที่สดใหม่และเต็มไปด้วยแร่ธาตุ",
        "pairing_en": "Seafood, Thai salads, and goat cheese.",
        "pairing_th": "อาหารทะเล สลัดไทย และชีสแพะ",
        "service_temperature": "8-10°C",
        "vintage": "2022",
        "sku": "PDBL-025",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "650 + VAT"
      },
      {
        "name": "Les Parcelles Delatour<br>Bordeaux Rouge",
        "slug": "les-parcelles-delatour-bordeaux-rouge",
        "region_en": "Bordeaux",
        "region_th": "บอร์โดซ์",
        "grape_varieties_en": "Merlot, Cabernet Sauvignon",
        "grape_varieties_th": "เมอร์โล, คาเบอร์เนต์ โซวิญง",
        "the_estate_en": "This entry-level Bordeaux is crafted for everyday enjoyment, showing bright fruit, freshness, and approachability.",
        "the_estate_th": "บอร์โดซ์ระดับเริ่มต้นนี้สร้างขึ้นสำหรับความเพลิดเพลินในชีวิตประจำวัน แสดงผลไม้สดใส ความสดใหม่ และความเข้าถึงได้",
        "terroir_en": "• Soil: Clay-limestone and gravel<br>• Grown in Entre-Deux-Mers area",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและกรวด<br>• ปลูกในพื้นที่อองเตร-เดอ-แมร์",
        "vinification_en": "• Fermented in stainless steel<br>• Short maceration for soft tannins",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• แมซอเรชันสั้นเพื่อแทนนินนุ่ม",
        "tasting_notes_en": "Light red fruit, touch of spice. Soft tannins and easy finish.",
        "tasting_notes_th": "ผลไม้แดงอ่อน สัมผัสของเครื่องเทศ แทนนินนุ่มและการจบที่ง่าย",
        "pairing_en": "Great with pizza, burgers, or pasta Bolognese.",
        "pairing_th": "ยอดเยี่ยมกับพิซซ่า เบอร์เกอร์ หรือพาสต้าโบโลเนเซ่",
        "service_temperature": "15-16°C",
        "vintage": "2022",
        "sku": "PDRG-026",
        "abv": "13%",
        "rating": "3.9",
        "price": "590 + VAT"
      }
    ]
  },
  {
    "region_slug": "rhone_valley",
    "wines": [
      {
        "name": "Cellier des Princes<br>Hauts des Coteaux Châteauneuf-du-Pape",
        "slug": "cellier-des-princes-hauts-des-coteaux-chateauneuf-du-pape",
        "region_en": "Châteauneuf-du-Pape, Rhône Valley",
        "region_th": "ชาโตว์เนิฟ-ดู-ปาป, โรน วัลเลย์",
        "grape_varieties_en": "90% Grenache, 5% Mourvèdre, 5% Syrah",
        "grape_varieties_th": "90% เกรอนาช, 5% มูร์เวดร์, 5% ซีราห์",
        "the_estate_en": "Cellier des Princes, producing Châteauneuf-du-Pape since 1925, helped create France's first AOC. After decades supplying top négociants, they took control in 2005, branding and selling their own wines. Today, their wines are enjoyed worldwide, showcasing heritage and excellence.",
        "the_estate_th": "Cellier des Princes ผลิตชาโตว์เนิฟ-ดู-ปาปตั้งแต่ปี 1925 ช่วยสร้าง AOC แรกของฝรั่งเศส หลังจากหลายทศวรรษที่จัดหาให้กับนักค้าชั้นนำ พวกเขาได้ควบคุมในปี 2005 สร้างแบรนด์และขายไวน์ของตัวเอง วันนี้ไวน์ของพวกเขาได้รับการเพลิดเพลินทั่วโลก แสดงให้เห็นมรดกและความเป็นเลิศ",
        "terroir_en": "• Hillside vineyards with rounded pebbles<br>• Locations: Courthézon, Bédarrides, and Sorgues",
        "terroir_th": "• ไร่องุ่นบนเนินเขาพร้อมกรวดกลม<br>• ที่ตั้ง: Courthézon, Bédarrides และ Sorgues",
        "vinification_en": "• Hand-picked at peak maturity<br>• Fast transport in small containers to avoid oxidation<br>• Destalking, 25-day fermentation, and daily pump-overs<br>• Controlled fermentation at 28–30°C<br>• Aged 12 months in oak barrels (1/3 new oak)<br>• Several months in bottle before release",
        "vinification_th": "• เก็บด้วยมือเมื่อสุกเต็ม<br>• ขนส่งเร็วในภาชนะเล็กเพื่อหลีกเลี่ยงการออกซิเดชัน<br>• การถอนก้าน หมัก 25 วัน และปั๊มทุกวัน<br>• การหมักที่ควบคุมที่ 28–30°C<br>• หมักอายุ 12 เดือนในถังไม้โอ๊ค (1/3 ไม้โอ๊คใหม่)<br>• หลายเดือนในขวดก่อนปล่อย",
        "tasting_notes_en": "A rich, powerful wine from 60-year-old vines, with complex aromas of vanilla, toast, and liquorice. Smooth tannins lead to a spicy, elegant finish.",
        "tasting_notes_th": "ไวน์ที่เข้มข้นและทรงพลังจากเถาไวน์อายุ 60 ปี พร้อมกลิ่นหอมซับซ้อนของวนิลลา ขนมปังปิ้ง และชะเอม แทนนินเรียบนำไปสู่การจบที่เผ็ดและสง่างาม",
        "pairing_en": "Perfect with beef bourguignon, venison filets with cranberry sauce, or refined cheeses.",
        "pairing_th": "เหมาะสมบูรณ์กับเนื้อวัว bourguignon เนื้อกวางฟิเลต์กับซอสแครนเบอร์รี่ หรือชีสที่ประณีต",
        "service_temperature": "15-17°C",
        "vintage": "2019",
        "sku": "CDPR-002",
        "abv": "15.5%",
        "rating": "4.1",
        "price": "1,750 + VAT"
      },
      {
        "name": "Cellier des Princes<br>Domaine de la Sainte Vierge Châteauneuf-du-Pape",
        "slug": "cellier-des-princes-domaine-de-la-sainte-vierge-chateauneuf-du-pape",
        "region_en": "Châteauneuf-du-Pape, Rhône Valley",
        "region_th": "ชาโตว์เนิฟ-ดู-ปาป, โรน วัลเลย์",
        "grape_varieties_en": "90% Grenache, 5% Mourvèdre, 5% Syrah",
        "grape_varieties_th": "90% เกรอนาช, 5% มูร์เวดร์, 5% ซีราห์",
        "the_estate_en": "Domaine de la Sainte Vierge is a historical vineyard within Cellier des Princes. The cooperative has been producing Châteauneuf-du-Pape wines since 1925, pioneering France's first AOC. Today, they continue to focus on small parcel vinification and traditional Rhône character.",
        "the_estate_th": "Domaine de la Sainte Vierge เป็นไร่องุ่นประวัติศาสตร์ภายใน Cellier des Princes สหกรณ์ได้ผลิตไวน์ชาโตว์เนิฟ-ดู-ปาปตั้งแต่ปี 1925 เป็นผู้บุกเบิก AOC แรกของฝรั่งเศส วันนี้พวกเขายังคงมุ่งเน้นการหมักแปลงขนาดเล็กและลักษณะโรนแบบดั้งเดิม",
        "terroir_en": "• Pebble-rich soils with limestone subsoil<br>• Plots located in Courthézon and surrounding communes",
        "terroir_th": "• ดินที่อุดมไปด้วยกรวดพร้อมดินชั้นล่างหินปูน<br>• แปลงตั้งอยู่ใน Courthézon และคอมมูนโดยรอบ",
        "vinification_en": "• Manual harvesting at optimal ripeness<br>• Fermentation in temperature-controlled tanks (28–30°C)<br>• Aged in oak barrels for 12 months<br>• Bottle aging before release",
        "vinification_th": "• การเก็บเกี่ยวด้วยมือในความสุกที่เหมาะสม<br>• การหมักในถังควบคุมอุณหภูมิ (28–30°C)<br>• หมักในถังไม้โอ๊คเป็นเวลา 12 เดือน<br>• การหมักอายุในขวดก่อนปล่อย",
        "tasting_notes_en": "Elegant nose with black cherry, licorice, and toasted spice. Smooth palate with well-integrated tannins and a persistent, silky finish.",
        "tasting_notes_th": "จมูกสง่างามด้วยเชอร์รี่เข้ม ชะเอม และเครื่องเทศคั่ว รสชาติเรียบเนียนพร้อมแทนนินที่ผสมผสานดีและการจบที่ต่อเนื่องและนุ่มนวล",
        "pairing_en": "Perfect with duck breast, beef stew, or aged cheeses.",
        "pairing_th": "เหมาะสมบูรณ์กับเนื้อเป็ดเบรสต์ สตูว์เนื้อวัว หรือชีสที่หมักแล้ว",
        "service_temperature": "16-18°C",
        "vintage": "2019",
        "sku": "CDPS-003",
        "abv": "15%",
        "rating": "4.0",
        "price": "1,690 + VAT"
      }
    ]
  },
  {
    "region_slug": "languedoc_and_provence",
    "wines": [
      {
        "name": "Château La Roque<br>Pic-Saint-Loup",
        "slug": "chateau-la-roque-pic-saint-loup",
        "region_en": "Pic-Saint-Loup, Languedoc",
        "region_th": "ปิก-แซงต์-ลู, ลังกืโดก",
        "grape_varieties_en": "50% Syrah, 40% Grenache, 10% Mourvèdre",
        "grape_varieties_th": "50% ซีราห์, 40% เกรอนาช, 10% มูร์เวดร์",
        "the_estate_en": "Château La Roque, located in Fontanès (Languedoc), is a certified organic and biodynamic estate. Their wines reflect the unique terroir and are crafted with care and precision.",
        "the_estate_th": "Château La Roque ตั้งอยู่ใน Fontanès (ลังกืโดก) เป็นไร่องุ่นที่ได้รับการรับรองออร์แกนิกและไบโอไดนามิก ไวน์ของพวกเขาสะท้อนถึงเทอร์รัวร์ที่เป็นเอกลักษณ์และสร้างขึ้นด้วยความใส่ใจและความแม่นยำ",
        "terroir_en": "• Agriculture: Organic & biodynamic<br>• Limestone soils typical of Pic-Saint-Loup",
        "terroir_th": "• การเกษตร: ออร์แกนิกและไบโอไดนามิก<br>• ดินหินปูนที่เป็นลักษณะเฉพาะของปิก-แซงต์-ลู",
        "vinification_en": "• Fermented in traditional or conical vats with indigenous yeasts<br>• Aged in concrete vats to preserve freshness and terroir",
        "vinification_th": "• หมักในถังแบบดั้งเดิมหรือรูปกรวยด้วยยีสต์พื้นเมือง<br>• หมักในถังคอนกรีตเพื่อรักษาความสดใหม่และเทอร์รัวร์",
        "tasting_notes_en": "Brilliant purple with purplish reflections. The nose is expressive with notes of fresh red fruits and spices. The palate is elegant, balanced, and silky with persistent freshness.",
        "tasting_notes_th": "สีม่วงเข้มพร้อมการสะท้อนสีม่วง จมูกแสดงออกด้วยโน้ตของผลไม้แดงสดและเครื่องเทศ รสชาติสง่างาม สมดุล และเนียนนุ่มพร้อมความสดใหม่ที่ต่อเนื่อง",
        "pairing_en": "Lamb tagine, braised chicken, marinated tuna skewers.",
        "pairing_th": "แลมบ์ตาจีน ไก่เบรสด์ เสียบทูน่าหมัก",
        "service_temperature": "16-18°C",
        "vintage": "2022",
        "sku": "LROQ-001",
        "abv": "14%",
        "rating": "3.9",
        "price": "980 + VAT"
      },
      {
        "name": "Vignobles Vellas<br>Marquis d'Orsay Languedoc Rouge",
        "slug": "vignobles-vellas-marquis-dorsay-languedoc-rouge",
        "region_en": "Teyran, Languedoc",
        "region_th": "เตรัง, ลังกืโดก",
        "grape_varieties_en": "Syrah, Grenache",
        "grape_varieties_th": "ซีราห์, เกรอนาช",
        "the_estate_en": "Vignobles Vellas is a family-owned winery established in 1996. Today it owns over 120 hectares of vineyards around Montpellier, producing creative and modern wines.",
        "the_estate_th": "Vignobles Vellas เป็นไร่องุ่นที่เป็นของครอบครัวก่อตั้งในปี 1996 วันนี้เป็นเจ้าของไร่องุ่นกว่า 120 เฮกตาร์รอบ Montpellier ผลิตไวน์ที่สร้างสรรค์และทันสมัย",
        "terroir_en": "• Soil: Clay-limestone<br>• Mediterranean climate",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• สภาพอากาศเมดิเตอร์เรเนียน",
        "vinification_en": "• Traditional vinification to preserve the purity of fruit and terroir<br>• Fermentation at low temperature<br>• Short aging in stainless steel tanks",
        "vinification_th": "• การหมักแบบดั้งเดิมเพื่อรักษาความบริสุทธิ์ของผลไม้และเทอร์รัวร์<br>• การหมักที่อุณหภูมิต่ำ<br>• การหมักอายุสั้นในถังสแตนเลสสตีล",
        "tasting_notes_en": "An intense ruby color with aromas of black fruits, spices, and licorice. Supple and balanced on the palate with a long finish.",
        "tasting_notes_th": "สีทับทิมเข้มพร้อมกลิ่นหอมของผลไม้เข้ม เครื่องเทศ และชะเอม นุ่มนวลและสมดุลในปากพร้อมการจบที่ยาวนาน",
        "pairing_en": "Perfect with grilled meats (lamb or poultry) and hearty dishes.",
        "pairing_th": "เหมาะสมบูรณ์กับเนื้อย่าง (แกะหรือสัตว์ปีก) และอาหารเข้มข้น",
        "service_temperature": "17°C",
        "vintage": "2022",
        "sku": "VIVE-002",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "740 + VAT"
      },
      {
        "name": "Vignobles Vellas<br>Castelet Saint Pierre Cuvée d'Exception Corbières",
        "slug": "vignobles-vellas-castelet-saint-pierre-cuvee-dexception-corbieres",
        "region_en": "Teyran, Languedoc",
        "region_th": "เตรัง, ลังกืโดก",
        "grape_varieties_en": "Syrah, Grenache Noir, Carignan",
        "grape_varieties_th": "ซีราห์, เกรอนาช นัวร์, คาริญาง",
        "the_estate_en": "Vignobles Vellas is a family-owned winery established in 1996. Known for producing rich and expressive wines with bold character and Mediterranean soul.",
        "the_estate_th": "Vignobles Vellas เป็นไร่องุ่นที่เป็นของครอบครัวก่อตั้งในปี 1996 เป็นที่รู้จักจากการผลิตไวน์ที่เข้มข้นและแสดงออกพร้อมลักษณะกล้าหาญและจิตวิญญาณเมดิเตอร์เรเนียน",
        "terroir_en": "• Soil: Clay-limestone, located on hillside terraces",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน ตั้งอยู่บนระเบียงเนินเขา",
        "vinification_en": "• Partial whole grape fermentation for added texture and complexity<br>• Traditional maceration followed by short aging in oak barrels",
        "vinification_th": "• การหมักองุ่นทั้งผลบางส่วนเพื่อเพิ่มเนื้อสัมผัสและความซับซ้อน<br>• การแมซอเรชันแบบดั้งเดิมตามด้วยการหมักอายุสั้นในถังไม้โอ๊ค",
        "tasting_notes_en": "A dark color with purple hues, offering beautiful complexity of ripe black fruit and spices. Full-bodied with velvety tannins.",
        "tasting_notes_th": "สีเข้มพร้อมสีม่วง เสนอความซับซ้อนที่สวยงามของผลไม้เข้มสุกและเครื่องเทศ เต็มตัวพร้อมแทนนินกำมะหยี่",
        "pairing_en": "Perfect with stewed dishes and hearty cuisine.",
        "pairing_th": "เหมาะสมบูรณ์กับอาหารสตูว์และอาหารเข้มข้น",
        "service_temperature": "17°C",
        "vintage": "Non vintage",
        "sku": "VIVE-001",
        "abv": "14%",
        "rating": "4.1",
        "price": "760 + VAT"
      },
      {
        "name": "Château Val Joanis<br>Les Aubépines Luberon",
        "slug": "chateau-val-joanis-les-aubepines-luberon",
        "region_en": "Luberon, Rhône Valley",
        "region_th": "ลูเบรง, โรน วัลเลย์",
        "grape_varieties_en": "70% Roussanne, 30% Rolle",
        "grape_varieties_th": "70% รูซานน์, 30% โรลล์",
        "the_estate_en": "Château Val Joanis is located in the Vaucluse, with 186 hectares of vines surrounded by olive groves and forests. The estate is certified HVE3 and produces elegant wines with strong character.",
        "the_estate_th": "Château Val Joanis ตั้งอยู่ใน Vaucluse พร้อมเถาไวน์ 186 เฮกตาร์ล้อมรอบด้วยต้นมะกอกและป่าไผ่ ไร่องุ่นได้รับการรับรอง HVE3 และผลิตไวน์ที่สง่างามพร้อมลักษณะที่แข็งแกร่ง",
        "terroir_en": "• A single plot located south of the estate<br>• Clay-limestone soils",
        "terroir_th": "• แปลงเดียวตั้งอยู่ทางใต้ของไร่องุ่น<br>• ดินเหนียว-หินปูน",
        "vinification_en": "• Skin contact maceration<br>• Fermented and matured in French oak barrels<br>• Aged on lees with regular bâtonnage",
        "vinification_th": "• การแมซอเรชันสัมผัสผิวหนัง<br>• หมักและหมักอายุในถังไม้โอ๊คฝรั่งเศส<br>• หมักอายุบนตะกอนพร้อมการกวนสม่ำเสมอ",
        "tasting_notes_en": "A refined and complex white wine, with notes of white peach, acacia flowers, and toasted brioche. Round and rich with a long mineral finish.",
        "tasting_notes_th": "ไวน์ขาวที่ประณีตและซับซ้อน พร้อมโน้ตของลูกพีชขาว ดอกอาคาเซีย และบริโอช์คั่ว กลมกล่อมและเข้มข้นพร้อมการจบที่ยาวนานเต็มไปด้วยแร่ธาตุ",
        "pairing_en": "Perfect with grilled fish, poultry in sauce, or creamy cheeses.",
        "pairing_th": "เหมาะสมบูรณ์กับปลาย่าง สัตว์ปีกในซอส หรือชีสครีมมี่",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "VAJO-002",
        "abv": "13.5%",
        "rating": "4.2",
        "price": "880 + VAT"
      },
      {
        "name": "Château Val Joanis<br>Les Griottes Luberon",
        "slug": "chateau-val-joanis-les-griottes-luberon",
        "region_en": "Luberon, Rhône Valley",
        "region_th": "ลูเบรง, โรน วัลเลย์",
        "grape_varieties_en": "Syrah, Grenache",
        "grape_varieties_th": "ซีราห์, เกรอนาช",
        "the_estate_en": "Château Val Joanis is an estate in the southern Rhône, producing wines with a strong Mediterranean identity. The Les Griottes cuvée is named after the wild cherry trees growing near the vineyard.",
        "the_estate_th": "Château Val Joanis เป็นไร่องุ่นในโรนใต้ ผลิตไวน์ที่มีเอกลักษณ์เมดิเตอร์เรเนียนที่แข็งแกร่ง คิวเว่ Les Griottes ได้ชื่อมาจากต้นเชอร์รี่ป่าที่เติบโตใกล้ไร่องุ่น",
        "terroir_en": "• Terraced vineyards<br>• Clay-limestone soils with good drainage",
        "terroir_th": "• ไร่องุ่นระเบียง<br>• ดินเหนียว-หินปูนพร้อมการระบายน้ำที่ดี",
        "vinification_en": "• Traditional vinification in stainless steel tanks<br>• Short aging to preserve freshness and fruit purity",
        "vinification_th": "• การหมักแบบดั้งเดิมในถังสแตนเลสสตีล<br>• การหมักอายุสั้นเพื่อรักษาความสดใหม่และความบริสุทธิ์ของผลไม้",
        "tasting_notes_en": "Bright garnet red with aromas of ripe cherries and spice. Supple and fresh with soft tannins and vibrant fruit on the finish.",
        "tasting_notes_th": "สีแดงโกเมนสดใสพร้อมกลิ่นหอมของเชอร์รี่สุกและเครื่องเทศ นุ่มนวลและสดใหม่พร้อมแทนนินนุ่มและผลไม้สดใสในการจบ",
        "pairing_en": "Grilled vegetables, white meats, and soft cheeses.",
        "pairing_th": "ผักย่าง เนื้อสีขาว และชีสนุ่ม",
        "service_temperature": "15-17°C",
        "vintage": "2022",
        "sku": "VAJO-003",
        "abv": "13.5%",
        "rating": "3.8",
        "price": "790 + VAT"
      }
    ]
  },
  {
    "region_slug": "loire_valley",
    "wines": [
      {
        "name": "Château Gigognan<br>Clos du Roi Châteauneuf-du-Pape",
        "slug": "chateau-gigognan-clos-du-roi-chateauneuf-du-pape",
        "region_en": "Châteauneuf-du-Pape, Rhône Valley",
        "region_th": "ชาโตว์เนิฟ-ดู-ปาป, โรน วัลเลย์",
        "grape_varieties_en": "Grenache, Syrah, Mourvèdre",
        "grape_varieties_th": "เกรอนาช, ซีราห์, มูร์เวดร์",
        "the_estate_en": "Château Gigognan is an organic-certified estate located near Sorgues, producing classic southern Rhône wines with elegance and depth. Clos du Roi is their flagship cuvée.",
        "the_estate_th": "Château Gigognan เป็นไร่องุ่นที่ได้รับการรับรองออร์แกนิกตั้งอยู่ใกล้ Sorgues ผลิตไวน์โรนใต้คลาสสิกด้วยความสง่างามและความลึก Clos du Roi เป็นคิวเว่เรือธงของพวกเขา",
        "terroir_en": "• Soil: Pebbly limestone and red clay<br>• Certified organic vineyards",
        "terroir_th": "• ดิน: หินปูนกรวดและดินเหนียวแดง<br>• ไร่องุ่นที่ได้รับการรับรองออร์แกนิก",
        "vinification_en": "• Manual harvest and sorting<br>• Aged in oak barrels for 12-15 months",
        "vinification_th": "• การเก็บเกี่ยวและคัดแยกด้วยมือ<br>• หมักในถังไม้โอ๊คเป็นเวลา 12-15 เดือน",
        "tasting_notes_en": "Black cherry, garrigue, and spice on the nose. Full-bodied with fine tannins and long, earthy finish.",
        "tasting_notes_th": "เชอร์รี่เข้ม การิก และเครื่องเทศในจมูก เต็มตัวพร้อมแทนนินละเอียดและการจบที่ยาวนาน เต็มไปด้วยเอิร์ธี่",
        "pairing_en": "Lamb chops, cassoulet, or grilled aubergine.",
        "pairing_th": "แลมบ์ช็อป แคซูเล หรือมะเขือย่าง",
        "service_temperature": "17-18°C",
        "vintage": "2020",
        "sku": "CGCP-027",
        "abv": "14.5%",
        "rating": "4.3",
        "price": "1,590 + VAT"
      },
      {
        "name": "Le Grand Rouvière<br>Côtes de Provence Rosé",
        "slug": "le-grand-rouviere-cotes-de-provence-rose",
        "region_en": "Côtes de Provence, Provence",
        "region_th": "โคต เดอ โปรวองซ์, โปรวองซ์",
        "grape_varieties_en": "Grenache, Cinsault, Syrah",
        "grape_varieties_th": "เกรอนาช, แซงโซ, ซีราห์",
        "the_estate_en": "Produced by the Domaine du Grand Rouvière, this elegant Provence rosé reflects the sunny Mediterranean terroir with balance and finesse.",
        "the_estate_th": "ผลิตโดย Domaine du Grand Rouvière โรเซ่โปรวองซ์ที่สง่างามนี้สะท้อนถึงเทอร์รัวร์เมดิเตอร์เรเนียนที่แสงแดดจัดพร้อมความสมดุลและความประณีต",
        "terroir_en": "• Soil: Clay-limestone with quartz pebbles<br>• Mediterranean climate with sea breeze influence",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนกับกรวดควอตซ์<br>• สภาพอากาศเมดิเตอร์เรเนียนที่มีอิทธิพลจากลมทะเล",
        "vinification_en": "• Direct press rosé<br>• Fermented at low temperature in stainless steel",
        "vinification_th": "• โรเซ่แบบกดโดยตรง<br>• หมักที่อุณหภูมิต่ำในสแตนเลสสตีล",
        "tasting_notes_en": "Pale salmon color. Fresh and aromatic with notes of wild strawberry, white peach, and citrus. Crisp and dry finish.",
        "tasting_notes_th": "สีแซลมอนอ่อน สดใหม่และหอมด้วยโน้ตของสตรอเบอร์รี่ป่า ลูกพีชขาว และส้ม การจบที่คมและแห้ง",
        "pairing_en": "Aperitif, seafood, summer salads, and Provençal dishes.",
        "pairing_th": "เครื่องดื่มเปิดมื้อ อาหารทะเล สลัดฤดูร้อน และอาหารโปรวองซ์",
        "service_temperature": "8-10°C",
        "vintage": "2022",
        "sku": "LGRR-028",
        "abv": "12.5%",
        "rating": "4.1",
        "price": "690 + VAT"
      }
    ]
  }
];

export function getWineBySlug(slug: string): (Wine & { region_slug: string }) | undefined {
  for (const region of winesByRegion) {
    const wine = region.wines.find(wine => wine.slug === slug);
    if (wine) return { ...wine, region_slug: region.region_slug };
  }
  return undefined;
}

export function getAllWineSlugs(): string[] {
  const slugs: string[] = [];
  for (const region of winesByRegion) {
    slugs.push(...region.wines.map(wine => wine.slug));
  }
  return slugs;
}

export function getAllWines(): (Wine & { region_slug: string })[] {
  const allWines: (Wine & { region_slug: string })[] = [];
  for (const region of winesByRegion) {
    allWines.push(...region.wines.map(wine => ({ ...wine, region_slug: region.region_slug })));
  }
  return allWines;
} 