export interface Wine {
  name: string;
  slug: string;
  region_en: string;
  region_th: string;
  grape_varieties_en: string;
  grape_varieties_th: string;
  the_estate_en: string;
  the_estate_th: string;
  terroir_en: string;
  terroir_th: string;
  vinification_en: string;
  vinification_th: string;
  tasting_notes_en: string;
  tasting_notes_th: string;
  pairing_en: string;
  pairing_th: string;
  service_temperature: string;
  vintage: string;
  sku: string;
  abv: string;
  rating: string;
  price: string;
}

export interface WineRegion {
  region_slug: string;
  wines: Wine[];
}

export const winesByRegion: WineRegion[] = [
  {
    "region_slug": "champagne",
    "wines": [
      {
        "name": "Prestige des Sacres<br>Brut Nature Champagne",
        "slug": "prestige-des-sacres-brut-nature-champagne",
        "region_en": "Champagne, Montagne de Reims",
        "region_th": "แชมเปญ, มงตาญเดอแรงส์",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 0 g/L (no added sugar)<br>• Aged over 4 years in cellars, followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 0 กรัม/ลิตร (ไม่เติมน้ำตาล)<br>• หมักอายุกว่า 4 ปีในห้องเก็บ ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A brilliant pale gold color with rapid, energetic bubbles. The nose reveals biscuit and toasted almonds, with citrus and white flower notes. Aeration brings out minerality, white pepper, dried fruit, and honey. The palate is lively and pure, with citrus-driven acidity, a silky texture, and a long, precise finish.",
        "tasting_notes_th": "สีทองอ่อนสดใสพร้อมฟองอากาศที่เร็วและมีพลัง กลิ่นเผยให้เห็นบิสกิตและอัลมอนด์คั่ว พร้อมด้วยโน้ตส้มและดอกไม้สีขาว การเติมอากาศทำให้เกิดแร่ธาตุ พริกไทยขาว ผลไม้แห้ง และน้ำผึ้ง รสชาติมีชีวิตชีวาและบริสุทธิ์ ด้วยความเป็นกิดจากส้ม เนื้อสัมผัสเนียนนุ่ม และการจบที่ยาวนานและแม่นยำ",
        "pairing_en": "Best enjoyed with seafood (oysters, caviar), Parmesan or Pecorino, and as an aperitif for Champagne purists.",
        "pairing_th": "เหมาะที่สุดกับอาหารทะเล (หอยนางรม, คาเวียร์), พาร์เมซานหรือเปโครีโน และเป็นเครื่องดื่มเปิดมื้อสำหรับผู้ที่ชื่นชอบแชมเปญแท้จริง",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-002",
        "abv": "12.5%",
        "rating": "4.2",
        "price": "1,670 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Brut Prestige Champagne",
        "slug": "prestige-des-sacres-brut-prestige-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Fermented with a balanced dosage of 9-9.5 g/L<br>• Aged in cellars for 4 years, followed by 6 months in bottle post-disgorgement",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• หมักด้วยโดสาจที่สมดุล 9-9.5 กรัม/ลิตร<br>• หมักในห้องเก็บเป็นเวลา 4 ปี ตามด้วย 6 เดือนในขวดหลังการดีกอร์จมอง",
        "tasting_notes_en": "Pale yellow with green highlights and fine bubbles. Dominant citrus notes of grapefruit and tangerine, followed by floral hints and candied lemon. Fresh, mineral-driven palate with lingering acidity and a creamy texture.",
        "tasting_notes_th": "สีเหลืองอ่อนพร้อมไฮไลท์สีเขียวและฟองอากาศละเอียด โน้ตส้มโดดเด่นของเกรปฟรุตและส้มแมนดาริน ตามด้วยกลิ่นดอกไม้และมะนาวหวาน รสชาติสดชื่น ขับเคลื่อนด้วยแร่ธาตุ พร้อมความเป็นกิดที่คงอยู่และเนื้อสัมผัสครีมมี่",
        "pairing_en": "Ideal as an aperitif or paired with seafood (lobster, shrimp, shellfish), white meats, and mild cheeses like Brie and Camembert.",
        "pairing_th": "เหมาะเป็นเครื่องดื่มเปิดมื้อหรือจับคู่กับอาหารทะเล (กุ้งมังกร, กุ้ง, หอย), เนื้อสีขาว และชีสอ่อนๆ เช่น บรีและคามแบร์",
        "service_temperature": "16-18°C",
        "vintage": "Non vintage",
        "sku": "PRSA-001",
        "abv": "12.5%",
        "rating": "3.8",
        "price": "1,570 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>30&3 Extra Brut Champagne",
        "slug": "prestige-des-sacres-30-3-extra-brut-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "30% Meunier vinified in oak, 70% Chardonnay",
        "grape_varieties_th": "30% มูนิเยร์หมักในไม้โอ๊ค, 70% ชาร์ดอนเนย์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• Dosage: 3 g/L<br>• Aged over 5 years in cellars,<br>  followed by 6-12 months in bottle",
        "vinification_th": "• โดสาจ: 3 กรัม/ลิตร<br>• หมักอายุกว่า 5 ปีในห้องเก็บ<br>  ตามด้วย 6-12 เดือนในขวด",
        "tasting_notes_en": "A golden hue with lively bubbles. Aromas of cooked quince, honey, warm toast, and spices. The palate is rich yet mineral-driven, with cooked fruit and saline minerality leading to a persistent, cocoa-tinged finish.",
        "tasting_notes_th": "สีทองพร้อมฟองอากาศที่มีชีวิตชีวา กลิ่นหอมของควินซ์ปรุงสุก น้ำผึ้ง ขนมปังปิ้งอุ่น และเครื่องเทศ รสชาติเข้มข้นแต่ขับเคลื่อนด้วยแร่ธาตุ พร้อมผลไม้ปรุงสุกและแร่ธาตุเค็มนำไปสู่การจบที่ยาวนานและมีกลิ่นโกโก้",
        "pairing_en": "Pairs well with veal, pork, lamb, and creamy, earthy dishes.",
        "pairing_th": "เข้ากันดีกับเนื้อลูกวัว เนื้อหมู เนื้อแกะ และอาหารครีมมี่รสเอิร์ธี่",
        "service_temperature": "10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-006",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "2,230 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Cuvée Dynastie Blanc de Blancs Brut Champagne",
        "slug": "prestige-des-sacres-cuvee-dynastie-blanc-de-blancs-brut-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 8-9 g/L<br>• Aged for 4 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 8-9 กรัม/ลิตร<br>• หมักเป็นเวลา 4 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A pale yellow robe with green highlights and fine bubbles. Citrus notes of grapefruit and tangerine dominate, followed by floral hints and candied lemon. The palate is fresh and mineral-driven, with lingering acidity and a creamy texture.",
        "tasting_notes_th": "เสื้อคลุมสีเหลืองอ่อนพร้อมไฮไลท์สีเขียวและฟองอากาศละเอียด โน้ตส้มของเกรปฟรุตและส้มแมนดารินเด่นชัด ตามด้วยกลิ่นดอกไม้และมะนาวหวาน รสชาติสดชื่นและขับเคลื่อนด้วยแร่ธาตุ พร้อมความเป็นกิดที่คงอยู่และเนื้อสัมผัสครีมมี่",
        "pairing_en": "Best as an aperitif or with delicate seafood, sushi, and sashimi.",
        "pairing_th": "ดีที่สุดเป็นเครื่องดื่มเปิดมื้อหรือกับอาหารทะเลละเอียดอ่อน ซูชิ และซาชิมิ",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-003",
        "abv": "12.5%",
        "rating": "3.9",
        "price": "1,950 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Cuvée Grenat Millésime Champagne",
        "slug": "prestige-des-sacres-cuvee-grenat-millesime-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "50% Chardonnay, 50% Pinot Noir",
        "grape_varieties_th": "50% ชาร์ดอนเนย์, 50% ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 100% vintage 2015 wine<br>• Dosage: 9.9 g/L<br>• Aged for over 5 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์วินเทจ 2015 100%<br>• โดสาจ: 9.9 กรัม/ลิตร<br>• หมักเป็นเวลากว่า 5 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A golden-green hue with fine bubbles. Aromas of mirabelle plum, vetiver, pastry, and forest notes. The palate is rich and dense, with creamy honey flavors and a touch of zesty astringency, leading to a long, harmonious finish.",
        "tasting_notes_th": "สีทอง-เขียวพร้อมฟองอากาศละเอียด กลิ่นหอมของมิราเบลล์พลัม เวติเวอร์ เปสตรี้ และโน้ตป่าไผ่ รสชาติเข้มข้นและหนาแน่น พร้อมรสน้ำผึ้งครีมมี่และสัมผัสของความฝาดเปรี้ยวจี๊ด นำไปสู่การจบที่ยาวนานและกลมกลืน",
        "pairing_en": "Pairs well with creamy poultry dishes, veal, foie gras, and hearty stews.",
        "pairing_th": "เข้ากันดีกับอาหารสัตว์ปีกครีมมี่ เนื้อลูกวัว ฟัวกราส์ และสตูว์เข้มข้น",
        "service_temperature": "10°C",
        "vintage": "2015",
        "sku": "PRSA-004",
        "abv": "12.5%",
        "rating": "4.1",
        "price": "2,030 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Brut Rosé Champagne",
        "slug": "prestige-des-sacres-brut-rose-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "30% Chardonnay, 30% Pinot Noir, 40% Pinot Meunier with 15% vinified red",
        "grape_varieties_th": "30% ชาร์ดอนเนย์, 30% ปีโน นัวร์, 40% ปีโน มูนิเยร์ พร้อม 15% หมักแบบไวน์แดง",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 9-9.5 g/L<br>• Aged for 3 years in cellars,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 9-9.5 กรัม/ลิตร<br>• หมักเป็นเวลา 3 ปีในห้องเก็บ<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "A pale copper color with fine bubbles. The nose starts with wild berries and strawberries, evolving into caramel and butterscotch. The palate is round and juicy, featuring strawberry and kirsch cherry flavors with a fresh, tart finish.",
        "tasting_notes_th": "สีทองแดงอ่อนพร้อมฟองอากาศละเอียด กลิ่นเริ่มต้นด้วยเบอร์รี่ป่าและสตรอเบอร์รี่ พัฒนาไปสู่คาราเมลและบัตเตอร์สก็อตช์ รสชาติกลมกล่อมและฉ่ำ โดดเด่นด้วยรสสตรอเบอร์รี่และเชอร์รี่เคิร์ช พร้อมการจบที่สดชื่นและเปรี้ยว",
        "pairing_en": "Pairs beautifully with charcuterie, prosciutto, Serrano ham, and fruity or chocolate-based desserts.",
        "pairing_th": "เข้ากันอย่างสวยงามกับชาร์คูเตอรี่ โปรชูตโต แฮมเซร์ราโน และขนมหวานที่มีผลไม้หรือช็อกโกแลตเป็นส่วนประกอบ",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-005",
        "abv": "12.5%",
        "rating": "3.9",
        "price": "1,820 + VAT"
      },
      {
        "name": "Prestige des Sacres<br>Demi-Sec Champagne",
        "slug": "prestige-des-sacres-demi-sec-champagne",
        "region_en": "Montagne de Reims, Champagne",
        "region_th": "มงตาญเดอแรงส์, แชมเปญ",
        "grape_varieties_en": "1/3 Chardonnay, 1/3 Pinot Meunier, 1/3 Pinot Noir",
        "grape_varieties_th": "1/3 ชาร์ดอนเนย์, 1/3 ปีโน มูนิเยร์, 1/3 ปีโน นัวร์",
        "the_estate_en": "Founded in the 1960s by René Lamblot and fellow winegrowers, Champagne Prestige des Sacres represents the expertise of 60 passionate growers. Their vineyards on the western slopes of the Montagne de Reims produce Champagnes that celebrate tradition and quality, honoring the historic coronations of French kings in Reims.",
        "the_estate_th": "ก่อตั้งในปี 1960 โดย René Lamblot และเพื่อนผู้ปลูกไวน์ แชมเปญ เพรสทีจ เดส์ ซาเคร์ เป็นตัวแทนของความเชี่ยวชาญของผู้ปลูกผู้หลงใหล 60 ราย ไร่องุ่นของพวกเขาบนเนินเขาทางตะวันตกของมงตาญเดอแรงส์ ผลิตแชมเปญที่เฉลิมฉลองประเพณีและคุณภาพ เพื่อเป็นเกียรติแก่การสถาปนากษัตริย์ฝรั่งเศสในประวัติศาสตร์ที่แรงส์",
        "terroir_en": "• Soil: Limestone and chalk<br>• Agriculture: Sustainable vineyard management",
        "terroir_th": "• ดิน: หินปูนและชอล์ก<br>• การเกษตร: การจัดการไร่องุ่นอย่างยั่งยืน",
        "vinification_en": "• 60% wine from the reference year, 40% reserve wines<br>• Dosage: 40 g/L<br>• Aged in cellars for 4 years,<br>  followed by 6 months in bottle",
        "vinification_th": "• ไวน์ 60% จากปีอ้างอิง, ไวน์สำรอง 40%<br>• โดสาจ: 40 กรัม/ลิตร<br>• หมักในห้องเก็บเป็นเวลา 4 ปี<br>  ตามด้วย 6 เดือนในขวด",
        "tasting_notes_en": "Aromas of shortbread, ripe mango, papaya, honey, and butterscotch. Sweet spices like cinnamon and nutmeg complement dried fruit notes. The palate is round and velvety, balancing acidity and effervescence with caramel and roasted nut flavors.",
        "tasting_notes_th": "กลิ่นหอมของช็อตเบรด มะม่วงสุก มะละกอ น้ำผึ้ง และบัตเตอร์สก็อตช์ เครื่องเทศหวานเช่นอบเชยและจันทน์เทศเสริมโน้ตผลไม้แห้ง รสชาติกลมกล่อมและนุ่มนวล สมดุลระหว่างความเป็นกิดและฟองอากาศ พร้อมรสคาราเมลและถั่วคั่ว",
        "pairing_en": "Perfect with blue cheeses (Roquefort, Stilton), foie gras, Asian sweet-and-sour dishes, and desserts.",
        "pairing_th": "เหมาะสมบูรณ์กับชีสบลู (โรคฟอร์ ส្ទิลตัน) ฟัวกราส์ อาหารเอเชียรสเปรี้ยวหวาน และขนมหวาน",
        "service_temperature": "8-10°C",
        "vintage": "Non vintage",
        "sku": "PRSA-007",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "1,650 + VAT"
      }
    ]
  },
  {
    "region_slug": "burgundy",
    "wines": [
      {
        "name": "Closerie des Alisiers<br>Vieilles Vignes Chablis 1er Cru",
        "slug": "closerie-des-alisiers-vieilles-vignes-chablis-1er-cru",
        "region_en": "Chablis, Burgundy",
        "region_th": "ชาบลิ, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Closerie des Alisiers is a boutique label that sources from old vines across the Chablis region. It focuses on showcasing terroir through minimal intervention and careful selection of plots with great aging potential.",
        "the_estate_th": "Closerie des Alisiers เป็นแบรนด์บูติกที่จัดหาจากเถาองุ่นแก่ทั่วภูมิภาคชาบลิ มุ่งเน้นการแสดงเทอร์รัวร์ผ่านการแทรกแซงเพียงเล็กน้อยและการคัดเลือกแปลงที่มีศักยภาพในการหมักที่ยอดเยี่ยม",
        "terroir_en": "• Soil: Kimmeridgian limestone rich in marine fossils<br>• Vineyard: 45-year-old vines from Premier Cru sites",
        "terroir_th": "• ดิน: หินปูนคิมเมอริเดียนอุดมไปด้วยฟอสซิลทางทะเล<br>• ไร่องุ่น: เถาองุ่นอายุ 45 ปีจากไซต์ Premier Cru",
        "vinification_en": "• Fermentation in stainless steel tanks<br>• Aged on lees for 10-12 months<br>• Minimal sulfur and no oak to preserve purity",
        "vinification_th": "• หมักในถังสแตนเลส<br>• หมักบนตะกอนเป็นเวลา 10-12 เดือน<br>• ใช้ซัลเฟอร์น้อยที่สุดและไม่ใช้ไม้โอ๊คเพื่อรักษาความบริสุทธิ์",
        "tasting_notes_en": "Fresh and intense on the nose, with citrus, flint, and white peach. The palate is crisp and mineral-driven, with chalky texture and long saline finish.",
        "tasting_notes_th": "สดชื่นและเข้มข้นในจมูก พร้อมส้ม หินไฟ และลูกพีชขาว รสชาติกรอบและขับเคลื่อนด้วยแร่ธาตุ พร้อมเนื้อสัมผัสชอล์กและการจบที่เค็มยาวนาน",
        "pairing_en": "Excellent with oysters, sea bass, grilled scallops, and goat cheese.",
        "pairing_th": "ยอดเยี่ยมกับหอยนางรม เซียเบส หอยเชลล์ย่าง และชีสแพะ",
        "service_temperature": "10-12°C",
        "vintage": "2021",
        "sku": "CLAL-001",
        "abv": "13%",
        "rating": "4.2",
        "price": "1,490 + VAT"
      },
      {
        "name": "Closerie des Alisiers<br>Petit Chablis",
        "slug": "closerie-des-alisiers-petit-chablis",
        "region_en": "Chablis, Burgundy",
        "region_th": "ชาบลิ, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Closerie des Alisiers is a small-scale négociant and micro-producer that selects grapes from top-quality vineyards in Chablis. The focus is on minimal intervention, clean vinification, and expressive terroir.",
        "the_estate_th": "Closerie des Alisiers เป็นผู้ค้าขนาดเล็กและผู้ผลิตไมโครที่คัดเลือกองุ่นจากไร่องุ่นคุณภาพสูงในชาบลิ เน้นการแทรกแซงเพียงเล็กน้อย การหมักที่สะอาด และเทอร์รัวร์ที่แสดงออก",
        "terroir_en": "• Soil: Portlandian limestone<br>• Vineyard: Young vines on high-altitude slopes",
        "terroir_th": "• ดิน: หินปูนพอร์ตแลนเดียน<br>• ไร่องุ่น: เถาองุ่นหนุ่มบนเนินเขาระดับสูง",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 6-8 months<br>• No oak used to preserve freshness",
        "vinification_th": "• หมักในสแตนเลส<br>• หมักบนตะกอนละเอียดเป็นเวลา 6-8 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่",
        "tasting_notes_en": "Lively and bright with aromas of green apple, citrus, and white flowers. The palate is zesty and clean with refreshing minerality and a crisp, dry finish.",
        "tasting_notes_th": "มีชีวิตชีวาและสดใสด้วยกลิ่นหอมของแอปเปิ้ลเขียว ส้ม และดอกไม้สีขาว รสชาติเปรี้ยวซ่าและสะอาด พร้อมแร่ธาตุที่สดชื่นและการจบที่กรอบและแห้ง",
        "pairing_en": "Great with shrimp cocktail, sushi, tempura, or fresh goat cheese.",
        "pairing_th": "ยอดเยี่ยมกับค็อกเทลกุ้ง ซูชิ เทมปุระ หรือชีสแพะสด",
        "service_temperature": "8-10°C",
        "vintage": "2022",
        "sku": "CLAL-002",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "990 + VAT"
      },
      {
        "name": "Closerie des Alisiers<br>Vieilles Vignes Marsannay",
        "slug": "closerie-des-alisiers-vieilles-vignes-marsannay",
        "region_en": "Marsannay, Côte de Nuits, Burgundy",
        "region_th": "มาร์ซันเน, โกต เดอ นูยต์, เบอร์กันดี",
        "grape_varieties_en": "100% Pinot Noir",
        "grape_varieties_th": "100% ปีโน นัวร์",
        "the_estate_en": "Closerie des Alisiers works closely with old-vine growers across Burgundy. In Marsannay, their focus is on expressive and structured Pinot Noir from some of the northernmost vineyards of the Côte de Nuits.",
        "the_estate_th": "Closerie des Alisiers ทำงานอย่างใกล้ชิดกับผู้ปลูกเถาองุ่นแก่ทั่วเบอร์กันดี ในมาร์ซันเน พวกเขามุ่งเน้นที่ปีโน นัวร์ที่แสดงออกและมีโครงสร้างจากไร่องุ่นที่อยู่ทางเหนือสุดของโกต เดอ นูยต์",
        "terroir_en": "• Soil: Clay-limestone with rocky subsoil<br>• Vineyard: Old vines (40+ years) from hillside plots",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนพร้อมชั้นดินล่างเป็นหิน<br>• ไร่องุ่น: เถาองุ่นแก่ (40+ ปี) จากแปลงบนเนินเขา",
        "vinification_en": "• Cold maceration before fermentation<br>• Fermented in stainless steel with indigenous yeasts<br>• Aged 12 months in French oak (20% new)",
        "vinification_th": "• แมซอเรชันเย็นก่อนการหมัก<br>• หมักในสแตนเลสสตีลด้วยยีสต์พื้นเมือง<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 20%)",
        "tasting_notes_en": "Aromas of dark cherry, red currant, and subtle earth. On the palate, it's juicy and structured with soft tannins and a mineral, peppery finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่เข้ม เรดเคอร์แรนต์ และดินเล็กน้อย ในปาก มีรสฉ่ำและมีโครงสร้าง พร้อมแทนนินนุ่มและการจบที่มีแร่ธาตุและเผ็ดร้อน",
        "pairing_en": "Perfect with roast chicken, pork tenderloin, duck confit, and firm cheeses.",
        "pairing_th": "เหมาะสมบูรณ์กับไก่ย่าง เนื้อหมูใน เป็ดคอนฟิต และชีสแข็ง",
        "service_temperature": "14-16°C",
        "vintage": "2021",
        "sku": "CLAL-003",
        "abv": "13%",
        "rating": "4.1",
        "price": "1,390 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Les Creuzettes Pouilly-Fuissé",
        "slug": "domaine-g-saumaize-les-creuzettes-pouilly-fuisse",
        "region_en": "Pouilly-Fuissé, Mâconnais, Burgundy",
        "region_th": "ปูยลีย์-ฟุยเซ, มาก็องเน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a small, family-run estate located in Vergisson, known for producing structured, age-worthy Chardonnay from exceptional terroirs in Pouilly-Fuissé. The Creuzettes plot is one of their prized lieux-dits, offering richness and elegance.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นขนาดเล็กที่ดำเนินการโดยครอบครัวที่ตั้งอยู่ในเวอร์ชิซง มีชื่อเสียงในการผลิตชาร์ดอนเนย์ที่มีโครงสร้างและมีอายุการเก็บจากเทอร์รัวร์ยอดเยี่ยมในปูยลีย์-ฟุยเซ แปลง Creuzettes เป็นหนึ่งใน lieux-dits ที่มีค่าของพวกเขา นำเสนอความเข้มข้นและความสง่างาม",
        "terroir_en": "• Soil: Clay-limestone with fossil-rich marl<br>• Altitude: 300 meters<br>• Vineyard: 40-year-old vines on southeast slopes",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนพร้อมมาร์ลที่อุดมไปด้วยฟอสซิล<br>• ระดับความสูง: 300 เมตร<br>• ไร่องุ่น: เถาองุ่นอายุ 40 ปีบนเนินทิศตะวันออกเฉียงใต้",
        "vinification_en": "• Fermentation in oak barrels (20% new)<br>• Aged 12 months on fine lees<br>• Light bâtonnage to enhance texture",
        "vinification_th": "• หมักในถังไม้โอ๊ค (ใหม่ 20%)<br>• หมักเป็นเวลา 12 เดือนบนตะกอนละเอียด<br>• บาโตนนาจเบาๆ เพื่อเสริมเนื้อสัมผัส",
        "tasting_notes_en": "Complex aromas of ripe pear, lemon peel, toasted almond, and white flowers. The palate is creamy yet precise, with vibrant acidity and a long mineral finish.",
        "tasting_notes_th": "กลิ่นหอมที่ซับซ้อนของลูกแพร์สุก เปลือกมะนาว อัลมอนด์คั่ว และดอกไม้สีขาว รสชาติครีมมี่แต่แม่นยำ พร้อมความเป็นกิดที่สดใสและการจบที่มีแร่ธาตุยาวนาน",
        "pairing_en": "Ideal with lobster, creamy poultry dishes, scallops, or aged Comté.",
        "pairing_th": "เหมาะสำหรับกุ้งมังกร อาหารสัตว์ปีกครีมมี่ หอยเชลล์ หรือ Comté ที่หมักแล้ว",
        "service_temperature": "10-12°C",
        "vintage": "2021",
        "sku": "SMPF-001",
        "abv": "13%",
        "rating": "4.3",
        "price": "1,750 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Mâcon-Davayé 'Les Belouzes'",
        "slug": "domaine-g-saumaize-macon-davaye-les-belouzes",
        "region_en": "Mâconnais, Burgundy",
        "region_th": "มาก็องเน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a traditional, family-operated estate in the village of Vergisson. They are known for crafting pure and terroir-driven Chardonnays in the Mâconnais region. 'Les Belouzes' comes from a high-quality lieu-dit in Davayé.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นแบบดั้งเดิมที่ดำเนินการโดยครอบครัวในหมู่บ้านเวอร์ชิซง พวกเขามีชื่อเสียงในการผลิตชาร์ดอนเนย์ที่บริสุทธิ์และขับเคลื่อนด้วยเทอร์รัวร์ในภูมิภาคมาก็องเน 'Les Belouzes' มาจาก lieu-dit คุณภาพสูงในดาวาเย",
        "terroir_en": "• Soil: Clay and limestone<br>• Exposure: Southeast-facing slope<br>• Vineyard: 35-year-old vines farmed sustainably",
        "terroir_th": "• ดิน: ดินเหนียวและหินปูน<br>• การหันหน้า: เนินเขาหันหน้าไปทางตะวันออกเฉียงใต้<br>• ไร่องุ่น: เถาองุ่นอายุ 35 ปีที่ปลูกอย่างยั่งยืน",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 10 months<br>• No oak to retain freshness and minerality",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• หมักบนตะกอนละเอียดเป็นเวลา 10 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่และแร่ธาตุ",
        "tasting_notes_en": "Bright and aromatic with notes of green apple, lemon zest, and crushed stones. Lively acidity and a clean, mineral finish make it highly refreshing.",
        "tasting_notes_th": "สดใสและหอมด้วยโน้ตของแอปเปิ้ลเขียว เปลือกมะนาวขูด และหินบด ความเป็นกิดที่มีชีวิตชีวาและการจบที่สะอาดมีแร่ธาตุทำให้สดชื่นอย่างมาก",
        "pairing_en": "Perfect with grilled prawns, chèvre salad, roast chicken, or steamed mussels.",
        "pairing_th": "เหมาะสมบูรณ์กับกุ้งย่าง สลัดเชฟร์ ไก่ย่าง หรือหอยแมลงภู่นึ่ง",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "SMMB-002",
        "abv": "13%",
        "rating": "4.1",
        "price": "990 + VAT"
      },
      {
        "name": "Domaine G. Saumaize<br>Bourgogne 'Les Prés Cousins'",
        "slug": "domaine-g-saumaize-bourgogne-les-pres-cousins",
        "region_en": "Burgundy",
        "region_th": "เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine G. Saumaize is a family estate located in Vergisson in the Mâconnais. Their Bourgogne-level wines come from carefully tended parcels near the Pouilly-Fuissé area, offering exceptional quality for the appellation.",
        "the_estate_th": "Domaine G. Saumaize เป็นไร่องุ่นครอบครัวที่ตั้งอยู่ในเวอร์ชิซงในมาก็องเน ไวน์ระดับเบอร์กองของพวกเขามาจากแปลงที่ได้รับการดูแลอย่างระมัดระวังใกล้กับพื้นที่ปูยลีย์-ฟุยเซ นำเสนอคุณภาพที่ยอดเยี่ยมสำหรับแอพเพลลาซง",
        "terroir_en": "• Soil: Clay-limestone<br>• Vineyard: 30-year-old vines located near Vergisson",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• ไร่องุ่น: เถาองุ่นอายุ 30 ปีที่ตั้งอยู่ใกล้เวอร์ชิซง",
        "vinification_en": "• Fermented in stainless steel<br>• Aged on fine lees for 10 months<br>• No oak to preserve freshness and purity",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• หมักบนตะกอนละเอียดเป็นเวลา 10 เดือน<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความสดใหม่และความบริสุทธิ์",
        "tasting_notes_en": "Fresh and floral with aromas of citrus, apple, and a hint of white peach. The palate is lively, round, and balanced with a crisp mineral finish.",
        "tasting_notes_th": "สดใหม่และหอมดอกไม้ด้วยกลิ่นหอมของส้ม แอปเปิ้ล และลูกพีชขาวเล็กน้อย รสชาติมีชีวิตชีวา กลม และสมดุล พร้อมการจบที่มีแร่ธาตุกรอบ",
        "pairing_en": "Ideal with grilled white fish, vegetable quiche, fresh cheeses, and seafood pasta.",
        "pairing_th": "เหมาะสำหรับปลาเนื้อขาวย่าง คิชผัก ชีสสด และพาสต้าซีฟู้ด",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "SMLP-003",
        "abv": "12.5%",
        "rating": "4.0",
        "price": "890 + VAT"
      },
      {
        "name": "Domaine MaldantPauvelot<br>Bourgogne Chardonnay",
        "slug": "domaine-maldant-pauvelot-bourgogne-chardonnay",
        "region_en": "Côte de Beaune, Burgundy",
        "region_th": "โกต เดอ โบน, เบอร์กันดี",
        "grape_varieties_en": "100% Chardonnay",
        "grape_varieties_th": "100% ชาร์ดอนเนย์",
        "the_estate_en": "Domaine Maldant Pauvelot is a family-run estate based in Chorey-lès-Beaune, known for producing elegant, terroir-driven wines across Burgundy. Their Bourgogne Chardonnay offers a refined expression of Côte de Beaune fruit with excellent value.",
        "the_estate_th": "Domaine Maldant Pauvelot เป็นไร่องุ่นที่ดำเนินการโดยครอบครัวที่ตั้งอยู่ในโชเร-เล-โบน มีชื่อเสียงในการผลิตไวน์ที่สง่างามและขับเคลื่อนด้วยเทอร์รัวร์ทั่วเบอร์กันดี ชาร์ดอนเนย์เบอร์กองของพวกเขานำเสนอการแสดงออกที่ประณีตของผลไม้โกต เดอ โบนด้วยคุณค่าที่ยอดเยี่ยม",
        "terroir_en": "• Soil: Limestone with clay deposits<br>• Vineyard: Multiple parcels near Chorey-lès-Beaune",
        "terroir_th": "• ดิน: หินปูนพร้อมตะกอนดินเหนียว<br>• ไร่องุ่น: แปลงหลายแปลงใกล้โชเร-เล-โบน",
        "vinification_en": "• Fermented in stainless steel vats<br>• Aged for 10 months on fine lees<br>• No oak used to preserve purity and freshness",
        "vinification_th": "• หมักในถังสแตนเลสสตีล<br>• หมักเป็นเวลา 10 เดือนบนตะกอนละเอียด<br>• ไม่ใช้ไม้โอ๊คเพื่อรักษาความบริสุทธิ์และความสดใหม่",
        "tasting_notes_en": "Elegant and fresh with aromas of pear, citrus, and white flowers. The palate is supple and mineral-driven with a clean, persistent finish.",
        "tasting_notes_th": "สง่างามและสดใหม่ด้วยกลิ่นหอมของลูกแพร์ ส้ม และดอกไม้สีขาว รสชาตินุ่มนวลและขับเคลื่อนด้วยแร่ธาตุ พร้อมการจบที่สะอาดและยาวนาน",
        "pairing_en": "Excellent with grilled chicken, seafood pasta, vegetable terrine, and soft cheeses.",
        "pairing_th": "ยอดเยี่ยมกับไก่ย่าง พาสต้าซีฟู้ด เทอร์รีนผัก และชีสนุ่ม",
        "service_temperature": "10-12°C",
        "vintage": "2022",
        "sku": "MPBC-001",
        "abv": "13%",
        "rating": "4.1",
        "price": "980 + VAT"
      },
      {
        "name": "Domaine Maldant Pauvelot<br>Bourgogne Pinot Noir",
        "slug": "domaine-maldant-pauvelot-bourgogne-pinot-noir",
        "region_en": "Côte de Beaune, Burgundy",
        "region_th": "โกต เดอ โบน, เบอร์กันดี",
        "grape_varieties_en": "100% Pinot Noir",
        "grape_varieties_th": "100% ปีโน นัวร์",
        "the_estate_en": "Domaine Maldant Pauvelot is a historic family estate located in Chorey-lès-Beaune. With a focus on precision and tradition, they produce elegant red wines that reflect the finesse of Pinot Noir from the Côte de Beaune.",
        "the_estate_th": "Domaine Maldant Pauvelot เป็นไร่องุ่นครอบครัวที่มีประวัติศาสตร์ตั้งอยู่ในโชเร-เล-โบน ด้วยการมุ่งเน้นความแม่นยำและประเพณี พวกเขาผลิตไวน์แดงที่สง่างามซึ่งสะท้อนถึงความประณีตของปีโน นัวร์จากโกต เดอ โบน",
        "terroir_en": "• Soil: Clay-limestone<br>• Vineyard: Parcels near Chorey-lès-Beaune and surrounding villages",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• ไร่องุ่น: แปลงใกล้โชเร-เล-โบนและหมู่บ้านโดยรอบ",
        "vinification_en": "• Traditional fermentation in stainless steel<br>• Aged 10 months in oak barrels (15% new)<br>• Gentle extraction to preserve fruit and finesse",
        "vinification_th": "• การหมักแบบดั้งเดิมในสแตนเลสสตีล<br>• หมักเป็นเวลา 10 เดือนในถังไม้โอ๊ค (ใหม่ 15%)<br>• การสกัดอย่างอ่อนโยนเพื่อรักษาผลไม้และความประณีต",
        "tasting_notes_en": "Vibrant red cherry and raspberry aromas with light spice and floral notes. The palate is soft and juicy with silky tannins and a mineral finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่แดงและราสเบอร์รี่ที่สดใส พร้อมเครื่องเทศเบาและโน้ตดอกไม้ รสชาตินุ่มและฉ่ำ พร้อมแทนนินนุ่มนวลและการจบที่มีแร่ธาตุ",
        "pairing_en": "Great with roast duck, grilled salmon, mushroom dishes, and charcuterie.",
        "pairing_th": "ยอดเยี่ยมกับเป็ดย่าง แซลมอนย่าง อาหารเห็ด และชาร์คูเตอรี่",
        "service_temperature": "14-16°C",
        "vintage": "2022",
        "sku": "MPPN-002",
        "abv": "13%",
        "rating": "4.0",
        "price": "980 + VAT"
      }
    ]
  },
  {
    "region_slug": "bordeaux",
    "wines": [
      {
        "name": "Château Croizet-Bages<br>Pauillac Grand Cru Classé",
        "slug": "chateau-croizet-bages-pauillac-grand-cru-classe",
        "region_en": "Pauillac, Bordeaux",
        "region_th": "โปยยัก, บอร์โดซ์",
        "grape_varieties_en": "70% Cabernet Sauvignon, 30% Merlot",
        "grape_varieties_th": "70% คาเบอร์เนต์ โซวิญง, 30% เมอร์โล",
        "the_estate_en": "A Fifth Growth Grand Cru Classé since 1855, Château Croizet-Bages is located on the Bages plateau near Château Lynch-Bages. With 30 hectares of prime gravel soils, the estate produces classic Pauillac with aging potential and finesse.",
        "the_estate_th": "เป็น Fifth Growth Grand Cru Classé ตั้งแต่ปี 1855 Château Croizet-Bages ตั้งอยู่บนที่ราบสูง Bages ใกล้กับ Château Lynch-Bages ด้วยที่ดิน 30 เฮกตาร์ของดินกรวดชั้นดี ไร่องุ่นแห่งนี้ผลิตโปยยักคลาสสิกที่มีศักยภาพในการบ่มและความประณีต",
        "terroir_en": "• Soil: Deep gravel over limestone subsoil<br>• Sustainable farming practices",
        "terroir_th": "• ดิน: กรวดลึกบนชั้นดินล่างหินปูน<br>• การปฏิบัติการเกษตรแบบยั่งยืน",
        "vinification_en": "• Stainless steel fermentation<br>• 12–16 months in French oak (50% new)",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• 12–16 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 50%)",
        "tasting_notes_en": "Concentrated aromas of cassis, cedar, and tobacco. Full-bodied and structured, with firm tannins and a long, earthy finish.",
        "tasting_notes_th": "กลิ่นหอมเข้มข้นของแคสซิส ซีดาร์ และยาสูบ เต็มตัวและมีโครงสร้าง พร้อมแทนนินแข็งและการจบที่ยาวนานและเอิร์ธี่",
        "pairing_en": "Best with grilled ribeye, roast lamb, or hard cheeses.",
        "pairing_th": "ดีที่สุดกับริบอายย่าง เนื้อแกะย่าง หรือชีสแข็ง",
        "service_temperature": "16–18°C",
        "vintage": "2017",
        "sku": "CBPA-001",
        "abv": "13.5%",
        "rating": "4.2",
        "price": "2,290 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Pauillac",
        "slug": "la-croix-des-aubrais-pauillac",
        "region_en": "Pauillac, Bordeaux",
        "region_th": "โปยยัก, บอร์โดซ์",
        "grape_varieties_en": "60% Cabernet Sauvignon, 40% Merlot",
        "grape_varieties_th": "60% คาเบอร์เนต์ โซวิญง, 40% เมอร์โล",
        "the_estate_en": "La Croix des Aubrais is crafted by a renowned Pauillac château to offer an accessible and food-friendly expression of this prestigious appellation.",
        "the_estate_th": "La Croix des Aubrais ถูกสร้างสรรค์โดยชาโตโปยยักที่มีชื่อเสียง เพื่อมอบการแสดงออกที่เข้าถึงได้และเป็นมิตรกับอาหารของแอพเพลลาซองที่มีเกียรติแห่งนี้",
        "terroir_en": "• Soil: Gravel and clay-limestone<br>• Traditional left bank terroir",
        "terroir_th": "• ดิน: กรวดและดินเหนียว-หินปูน<br>• เทอร์รัวร์ฝั่งซ้ายแบบดั้งเดิม",
        "vinification_en": "• Fermentation in temperature-controlled vats<br>• 12 months in oak barrels",
        "vinification_th": "• การหมักในถังควบคุมอุณหภูมิ<br>• 12 เดือนในถังไม้โอ๊ค",
        "tasting_notes_en": "Blackcurrant, graphite, and cedar on the nose. Structured and elegant, with polished tannins and dark fruit on the finish.",
        "tasting_notes_th": "แบล็กเคอร์แรนต์ กราไฟต์ และซีดาร์ในจมูก มีโครงสร้างและสง่างาม พร้อมแทนนินที่ขัดเงาและผลไม้เข้มในการจบ",
        "pairing_en": "Beef stew, roast duck, and aged gouda.",
        "pairing_th": "สตูว์เนื้อ เป็ดย่าง และเก๋าดาหมัก",
        "service_temperature": "16–18°C",
        "vintage": "2019",
        "sku": "CDAP-002",
        "abv": "13.5%",
        "rating": "4.0",
        "price": "1,290 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Saint-Julien",
        "slug": "la-croix-des-aubrais-saint-julien",
        "region_en": "Saint-Julien, Bordeaux",
        "region_th": "แซงต์-จูเลียง, บอร์โดซ์",
        "grape_varieties_en": "70% Cabernet Sauvignon, 25% Merlot, 5% Petit Verdot",
        "grape_varieties_th": "70% คาเบอร์เนต์ โซวิญง, 25% เมอร์โล, 5% เปอตี เวอร์โด",
        "the_estate_en": "Sourced from vineyards neighboring prestigious classified growths, this cuvée expresses the elegance and depth of Saint-Julien.",
        "the_estate_th": "ที่มาจากไร่องุ่นใกล้เคียงกับ classified growths ที่มีเกียรติ คิวเว่นี้แสดงออกถึงความสง่างามและความลึกของแซงต์-จูเลียง",
        "terroir_en": "• Soil: Deep gravel over limestone<br>• Classic Médoc terroir",
        "terroir_th": "• ดิน: กรวดลึกบนหินปูน<br>• เทอร์รัวร์เมดอกคลาสสิก",
        "vinification_en": "• Stainless steel vinification<br>• 12 months in oak (25% new)",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• 12 เดือนในไม้โอ๊ค (ใหม่ 25%)",
        "tasting_notes_en": "Elegant and refined with red plum, violet, and cedar aromas. Smooth tannins and excellent balance on the palate.",
        "tasting_notes_th": "สง่างามและประณีตด้วยกลิ่นหอมของพลัมแดง ไวโอเล็ต และซีดาร์ แทนนินเรียบและสมดุลยอดเยี่ยมในปาก",
        "pairing_en": "Lamb chops, mushroom risotto, and truffle cheese.",
        "pairing_th": "แลมบ์ช็อป ริซอตโต้เห็ด และชีสทรัฟเฟิล",
        "service_temperature": "16–18°C",
        "vintage": "2019",
        "sku": "CDAS-003",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,390 + VAT"
      },
      {
        "name": "La Croix des Aubrais<br>Pomerol",
        "slug": "la-croix-des-aubrais-pomerol",
        "region_en": "Pomerol, Bordeaux",
        "region_th": "โปเมรอล, บอร์โดซ์",
        "grape_varieties_en": "90% Merlot, 10% Cabernet Franc",
        "grape_varieties_th": "90% เมอร์โล, 10% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "La Croix des Aubrais Pomerol comes from clay-rich vineyards that typify the right bank, delivering rich and velvety Merlot-driven wines.",
        "the_estate_th": "La Croix des Aubrais Pomerol มาจากไร่องุ่นที่อุดมไปด้วยดินเหนียวซึ่งเป็นตัวแทนของฝั่งขวา มอบไวน์ที่ขับเคลื่อนด้วยเมอร์โลที่เข้มข้นและนุ่มนวล",
        "terroir_en": "• Soil: Blue clay and gravel<br>• Right bank microclimate",
        "terroir_th": "• ดิน: ดินเหนียวสีฟ้าและกรวด<br>• ไมโครคลิเมตฝั่งขวา",
        "vinification_en": "• Vinified in concrete and stainless steel<br>• Aged 14 months in French oak barrels",
        "vinification_th": "• หมักในคอนกรีตและสแตนเลสสตีล<br>• หมักเป็นเวลา 14 เดือนในถังไม้โอ๊คฝรั่งเศส",
        "tasting_notes_en": "Plum, mocha, and blackberry aromas lead into a lush palate with round tannins and generous fruit.",
        "tasting_notes_th": "กลิ่นหอมของพลัม โมคา และแบล็กเบอร์รี่นำไปสู่รสชาติที่เข้มข้น พร้อมแทนนินกลมและผลไม้ที่เอื้อเฟื้อ",
        "pairing_en": "Duck breast, veal, mushroom-based dishes, and truffled pasta.",
        "pairing_th": "เนื้อเป็ดอก เนื้อลูกวัว อาหารที่มีเห็ดเป็นฐาน และพาสต้าทรัฟเฟิล",
        "service_temperature": "16–17°C",
        "vintage": "2020",
        "sku": "CDAP-004",
        "abv": "14%",
        "rating": "4.2",
        "price": "1,490 + VAT"
      },
      {
        "name": "Château Lilian Ladouys<br>Saint-Estèphe",
        "slug": "chateau-lilian-ladouys-saint-estephe",
        "region_en": "Saint-Estèphe, Bordeaux",
        "region_th": "แซงต์-เอสเตฟ, บอร์โดซ์",
        "grape_varieties_en": "55% Merlot, 40% Cabernet Sauvignon, 5% Petit Verdot",
        "grape_varieties_th": "55% เมอร์โล, 40% คาเบอร์เนต์ โซวิญง, 5% เปอตี เวอร์โด",
        "the_estate_en": "A Cru Bourgeois Exceptionnel with a long history, Château Lilian Ladouys combines richness and finesse with increasing critical acclaim in recent vintages.",
        "the_estate_th": "Cru Bourgeois Exceptionnel ที่มีประวัติศาสตร์ยาวนาน Château Lilian Ladouys ผสมผสานความเข้มข้นและความประณีต พร้อมการยกย่องจากนักวิจารณ์ที่เพิ่มขึ้นในวินเทจล่าสุด",
        "terroir_en": "• Soil: Gravel and clay<br>• Vines average 35 years of age",
        "terroir_th": "• ดิน: กรวดและดินเหนียว<br>• เถาองุ่นอายุเฉลี่ย 35 ปี",
        "vinification_en": "• Fermentation in stainless steel<br>• Aged 14 months in French oak (30% new)",
        "vinification_th": "• การหมักในสแตนเลสสตีล<br>• หมักเป็นเวลา 14 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 30%)",
        "tasting_notes_en": "Ripe black fruits, tobacco, and spice on the nose. Broad and velvety with excellent structure and a mineral backbone.",
        "tasting_notes_th": "ผลไม้เข้มสุก ยาสูบ และเครื่องเทศในจมูก กว้างและนุ่มนวล พร้อมโครงสร้างที่ยอดเยี่ยมและแกนกระดูกแร่ธาตุ",
        "pairing_en": "Braised short ribs, roast beef, and hearty stews.",
        "pairing_th": "ซี่โครงสั้นต้ม เนื้อย่าง และสตูว์เข้มข้น",
        "service_temperature": "16–18°C",
        "vintage": "2018",
        "sku": "LLSE-005",
        "abv": "14%",
        "rating": "4.3",
        "price": "1,790 + VAT"
      },
      {
        "name": "Château de France<br>Pessac-Léognan",
        "slug": "chateau-de-france-pessac-leognan",
        "region_en": "Pessac-Léognan, Bordeaux",
        "region_th": "เปสซัก-เลโญง, บอร์โดซ์",
        "grape_varieties_en": "60% Cabernet Sauvignon, 40% Merlot",
        "grape_varieties_th": "60% คาเบอร์เนต์ โซวิญง, 40% เมอร์โล",
        "the_estate_en": "Château de France is a top-quality estate in Pessac-Léognan with a strong reputation for elegant, age-worthy wines with smoky complexity.",
        "the_estate_th": "Château de France เป็นไร่องุ่นคุณภาพสูงในเปสซัก-เลโญงที่มีชื่อเสียงอันแข็งแกร่งในด้านไวน์ที่สง่างาม มีอายุการเก็บ และมีความซับซ้อนแบบรมควัน",
        "terroir_en": "• Soil: Deep gravel over clay-limestone<br>• Located on one of the highest ridges in the appellation",
        "terroir_th": "• ดิน: กรวดลึกบนดินเหนียว-หินปูน<br>• ตั้งอยู่บนหนึ่งในสันเขาที่สูงที่สุดในแอพเพลลาซง",
        "vinification_en": "• Stainless steel vinification<br>• 12 months in French oak (30% new)",
        "vinification_th": "• การหมักไวน์ในสแตนเลสสตีล<br>• 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 30%)",
        "tasting_notes_en": "Black cherry, graphite, and smoked herbs. The palate is precise with firm tannins and great length.",
        "tasting_notes_th": "เชอร์รี่เข้ม กราไฟต์ และสมุนไพรรมควัน รสชาติแม่นยำพร้อมแทนนินแข็งและความยาวที่ยอดเยี่ยม",
        "pairing_en": "Grilled lamb, duck confit, and mushroom-based dishes.",
        "pairing_th": "แกะย่าง เป็ดคอนฟิต และอาหารที่มีเห็ดเป็นฐาน",
        "service_temperature": "16–18°C",
        "vintage": "2019",
        "sku": "CFPL-006",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,650 + VAT"
      },
      {
        "name": "Château Capet Duverger<br>Saint-Émilion Grand Cru",
        "slug": "chateau-capet-duverger-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "90% Merlot, 10% Cabernet Franc",
        "grape_varieties_th": "90% เมอร์โล, 10% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Located on limestone plateaus just outside the village of Saint-Émilion, Capet Duverger is a Grand Cru estate that emphasizes elegance, balance, and terroir expression.",
        "the_estate_th": "ตั้งอยู่บนที่ราบสูงหินปูนนอกหมู่บ้านแซงต์-เอมิลิยง Capet Duverger เป็นไร่องุ่น Grand Cru ที่เน้นความสง่างาม สมดุล และการแสดงออกของเทอร์รัวร์",
        "terroir_en": "• Soil: Clay-limestone<br>• Vines averaging 35 years old",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• เถาองุ่นอายุเฉลี่ย 35 ปี",
        "vinification_en": "• Fermentation in concrete vats<br>• 12 months aging in French oak (25% new)",
        "vinification_th": "• การหมักในถังคอนกรีต<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊คฝรั่งเศส (ใหม่ 25%)",
        "tasting_notes_en": "Aromas of red cherry, violet, and spice. Supple texture with freshness and a long, floral finish.",
        "tasting_notes_th": "กลิ่นหอมของเชอร์รี่แดง ไวโอเล็ต และเครื่องเทศ เนื้อสัมผัสนุ่มนวลพร้อมความสดใหม่และการจบที่ยาวนานและหอมดอกไม้",
        "pairing_en": "Perfect with duck confit, grilled lamb, or mushroom ragù.",
        "pairing_th": "เหมาะสมบูรณ์กับเป็ดคอนฟิต แกะย่าง หรือราคูเห็ด",
        "service_temperature": "16–17°C",
        "vintage": "2020",
        "sku": "CDSE-007",
        "abv": "13.5%",
        "rating": "4.1",
        "price": "1,290 + VAT"
      },
      {
        "name": "Château Tourbadon<br>Saint-Émilion Grand Cru",
        "slug": "chateau-tourbadon-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Château Tourbadon is a small Grand Cru estate producing concentrated, approachable wines from clay-limestone soils near the Saint-Émilion plateau.",
        "the_estate_th": "Château Tourbadon เป็นไร่องุ่น Grand Cru ขนาดเล็กที่ผลิตไวน์เข้มข้นและเข้าถึงได้ จากดินเหนียว-หินปูนใกล้ที่ราบสูงแซงต์-เอมิลิยง",
        "terroir_en": "• Soil: Clay-limestone and sandy loam<br>• Sustainably managed vineyards",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูนและดินร่วนทราย<br>• ไร่องุ่นที่จัดการอย่างยั่งยืน",
        "vinification_en": "• Fermented in stainless steel<br>• 12 months in oak barrels (20% new)",
        "vinification_th": "• หมักในสแตนเลสสตีล<br>• 12 เดือนในถังไม้โอ๊ค (ใหม่ 20%)",
        "tasting_notes_en": "Juicy red fruits, baking spices, and floral notes. Medium-bodied with soft tannins and a smooth finish.",
        "tasting_notes_th": "ผลไม้แดงฉ่ำ เครื่องเทศอบ และโน้ตดอกไม้ ตัวกลางพร้อมแทนนินนุ่มและการจบที่เรียบ",
        "pairing_en": "Pair with grilled meats, lentil stew, or roasted vegetables.",
        "pairing_th": "จับคู่กับเนื้อย่าง สตูว์ถั่วเลนทิล หรือผักย่าง",
        "service_temperature": "16–17°C",
        "vintage": "2020",
        "sku": "TBSE-008",
        "abv": "14%",
        "rating": "4.0",
        "price": "1,150 + VAT"
      },
      {
        "name": "Château Piney<br>Saint-Émilion Grand Cru",
        "slug": "chateau-piney-saint-emilion-grand-cru",
        "region_en": "Saint-Émilion, Bordeaux",
        "region_th": "แซงต์-เอมิลิยง, บอร์โดซ์",
        "grape_varieties_en": "85% Merlot, 15% Cabernet Franc",
        "grape_varieties_th": "85% เมอร์โล, 15% คาเบอร์เนต์ ฟรัง",
        "the_estate_en": "Château Piney is a family-run Grand Cru estate producing traditional right bank wines with structure and depth, located just east of the village of Saint-Émilion.",
        "the_estate_th": "Château Piney เป็นไร่องุ่น Grand Cru ที่ดำเนินการโดยครอบครัว ผลิตไวน์ฝั่งขวาแบบดั้งเดิมที่มีโครงสร้างและความลึก ตั้งอยู่ทางตะวันออกของหมู่บ้านแซงต์-เอมิลิยง",
        "terroir_en": "• Soil: Clay-limestone<br>• Old vines over 35 years of age",
        "terroir_th": "• ดิน: ดินเหนียว-หินปูน<br>• เถาองุ่นแก่อายุกว่า 35 ปี",
        "vinification_en": "• Cold maceration and stainless steel fermentation<br>• Aged 12 months in oak (25% new)",
        "vinification_th": "• แมซอเรชันเย็นและการหมักในสแตนเลสสตีล<br>• หมักเป็นเวลา 12 เดือนในไม้โอ๊ค (ใหม่ 25%)",
        "tasting_notes_en": "Blackberry, plum, and spice aromas. Rich and smooth palate with firm tannins and earthy notes.",
        "tasting_notes_th": "กลิ่นหอมของแบล็กเบอร์รี่ พลัม และเครื่องเทศ รสชาติเข้มข้นและเรียบ พร้อมแทนนินแข็งและโน้ตเอิร์ธี่",
        "pairing_en": "Delicious with roast duck, beef bourguignon, or grilled eggplant.",
        "pairing_th": "อร่อยกับเป็ดย่าง บีฟ บูร์กินยง หรือมะเขือย่าง",
        "service_temperature": "16–18°C",
        "vintage": "2020",
        "sku": "PNSE-009",
        "abv": "14%",
        "rating": "4.1",
        "price": "1,290 + VAT"
      }
    ]
  }
];

export function getWineBySlug(slug: string): (Wine & { region_slug: string }) | undefined {
  for (const region of winesByRegion) {
    const wine = region.wines.find(wine => wine.slug === slug);
    if (wine) return { ...wine, region_slug: region.region_slug };
  }
  return undefined;
}

export function getAllWineSlugs(): string[] {
  const slugs: string[] = [];
  for (const region of winesByRegion) {
    slugs.push(...region.wines.map(wine => wine.slug));
  }
  return slugs;
}

export function getAllWines(): (Wine & { region_slug: string })[] {
  const allWines: (Wine & { region_slug: string })[] = [];
  for (const region of winesByRegion) {
    allWines.push(...region.wines.map(wine => ({ ...wine, region_slug: region.region_slug })));
  }
  return allWines;
} 